#!/usr/bin/env python3
"""Export frozen adaptive handoff inputs/results for the production C tests.

This does not execute or regenerate retail expectations. Input geometry comes
from the preserved deterministic producer scenarios; outputs come only from the
frozen original-code fixtures, including the ten complete rare node tables.
"""
import argparse
import gzip
import hashlib
import json
from pathlib import Path
import struct
import sys

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(Path(__file__).with_name('research')))
from verify_acc01_2_witnesses import scenarios,base_fixtures,fine_of


def read(name):
    path=ROOT/'tools/ghidra/fixtures/research'/name
    data=path.read_bytes()
    if path.suffix=='.gz':data=gzip.decompress(data)
    return json.loads(data),hashlib.sha256(data).hexdigest()


def bits(value):
    return struct.unpack('<I',struct.pack('<f',value))[0]


def render():
    witness,wd=read('ACC-01.2-expected.json.gz')
    costs,cd=read('ACC-04.1-expected.json.gz')
    markers,md=read('ACC-02.2-expected.json')
    scenes=scenarios(ROOT/'tools/ghidra/fixtures/research/ACC-01.2-witness-maps.json')
    for name,blocked in base_fixtures():
        scenes.append(dict(name='transpose/'+name,fine=[(y,x) for x,y in fine_of(blocked)],gates=[]))
    scene_ids={s['name']:i for i,s in enumerate(scenes)}
    fine,gates,maps=[],[],[]
    for scene in scenes:
        cells=sorted(y*64+x for x,y in scene['fine'])
        gs=[[marker,*box,*dest,active] for marker,box,dest,active in scene['gates']]
        maps.append([scene['name'],len(fine),len(cells),len(gates),len(gs)])
        fine.extend(cells);gates.extend(gs)
    words,cases,route_offsets=[],[],{}
    def append_case(row,name,source,goal,work_key='work'):
        route=[int(w,16) for w in row['route_words']]
        key=tuple(route)
        if key not in route_offsets:
            route_offsets[key]=len(words);words.extend(route)
        values=[scene_ids[name],row.get('lane',0),row['size_input'],row.get('warp',0),
            row.get('budget',100000),*map(bits,source),*map(bits,goal),
            row['result'],row[work_key],row['nodes'],row.get('warp_count',0),route_offsets[key],len(route)//2]
        cases.append(values)
    for row in witness['rows']:
        append_case(row,row['ref'].split('#')[0],row['source'],row['goal'])
    for row in costs['part2_costs']['rows']:
        transpose=row['transposed'];source=(4.75,4.25) if transpose else (4.25,4.75)
        goal=(27.75,27.25) if transpose else (27.25,27.75)
        append_case(row,('transpose/' if transpose else 'std/')+row['map'],source,goal)
    details,nodes=[],[]
    by_key={(r['ref'],r['lane']):i for i,r in enumerate(witness['rows'])}
    for row in witness['details']:
        details.append([by_key[(row['ref'],row['lane'])],len(nodes),len(row['nodes'])])
        nodes.extend(row['nodes'])
    goals=[]
    for i,row in enumerate(costs['part2_costs']['rows']):
        if 'retail_goal_g' in row:goals.append([len(witness['rows'])+i,row['retail_goal_g']])
    budgets=[]
    for row in costs['part4_budget']['rows']:
        budgets.append([scene_ids['std/'+row['map']],row['size_input'],row['budget'],
            row['result'],row['work'],row['nodes'],row['nearest'],row['nearest_d2'],
            *map(bits,row['first_route_point'])])
    parents=[]
    for row in markers['B_reducer_paths']['rows']:
        child=[int(w,16) for w in row['child_words']]
        parents.append([*((w>>24)&255 for w in child),*((w>>16)&255 for w in child),
            *row['parent'],*row['parent_without_markers']])
    out=['/* Generated by tools/ghidra/generate_wc3_adaptive_witnesses.py.\n',
        ' * Frozen original-code SHA256 (uncompressed):\n',
        f' * ACC-01.2 {wd}\n * ACC-02.2 {md}\n * ACC-04.1 {cd}\n */\n']
    def table(ctype,name,rows,format_row):
        out.append(f'static {ctype} const {name}[]={{\n')
        out.extend('    '+format_row(row)+',\n' for row in rows);out.append('};\n\n')
    table('uint16_t','retail_acc_fine_cells',[fine[i:i+16] for i in range(0,len(fine),16)],lambda r:','.join(map(str,r)))
    table('retailAccMap_t','retail_acc_maps',maps,lambda r:'{'+json.dumps(r[0])+','+','.join(map(str,r[1:]))+'}')
    table('retailAccGate_t','retail_acc_gates',gates,lambda r:'{'+','.join(map(str,r))+'}')
    table('uint32_t','retail_acc_route_words',[words[i:i+8] for i in range(0,len(words),8)],lambda r:','.join(f'0x{w:08x}u' for w in r))
    table('retailAccCase_t','retail_acc_cases',cases,lambda r:'{'+','.join(map(str,r[:5]))+',{' +','.join(f'0x{w:08x}u' for w in r[5:9])+'},'+','.join(map(str,r[9:]))+'}')
    table('retailAccDetail_t','retail_acc_details',details,lambda r:'{'+','.join(map(str,r))+'}')
    table('int32_t','retail_acc_node_words',nodes,lambda r:','.join(map(str,r)))
    table('retailAccGoal_t','retail_acc_goals',goals,lambda r:'{'+','.join(map(str,r))+'}')
    table('retailAccBudget_t','retail_acc_budgets',budgets,lambda r:'{'+','.join(map(str,r[:8]))+',{' +','.join(f'0x{w:08x}u' for w in r[8:])+'}}')
    table('retailAccParent_t','retail_acc_parents',parents,lambda r:'{{'+','.join(map(str,r[:4]))+'},{'+','.join(map(str,r[4:8]))+'},{'+','.join(map(str,r[8:12]))+'},{'+','.join(map(str,r[12:]))+'}}')
    return ''.join(out).rstrip()+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=ROOT/'games/warcraft-3/game/tests/retail_adaptive_witnesses.h')
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args();content=render()
    if args.check:
        if args.output.read_text()!=content:raise SystemExit('adaptive witness export differs')
    else:args.output.write_text(content)


if __name__=='__main__':main()
