#!/usr/bin/env python3
"""Regenerate retail scalar tables independently, without reading a retail binary."""
from decimal import Decimal, localcontext
import hashlib
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[2]
PI = Decimal('3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628')


def sine_table():
    with localcontext() as context:
        context.prec = 90
        table = []
        for i in range(1025):
            x = PI * i / 2048
            total = term = x
            for n in range(1,100):
                term *= -x*x / ((2*n)*(2*n+1))
                total += term
                if abs(term) < Decimal('1e-85'):
                    break
            table.append(min(int(total*(1 << 31)), 0x7fffffff))
        return table


def reciprocal_table():
    # Samples are at the preceding raw significand word, saturating the left endpoint.
    return [min(0x800000, (1 << 47) // (0x800000+i*8192-1) - 0x800000) for i in range(1025)]


def decimal_acos(x):
    if not x: return PI/2
    if x == 1: return Decimal(0)
    y = ((1-x)/(1+x)).sqrt()
    scale = 2
    while y > Decimal('0.1'):
        y /= 1+(1+y*y).sqrt()
        scale *= 2
    total = term = y
    for n in range(1,100):
        term *= -y*y
        total += term/(2*n+1)
        if abs(term) < Decimal('1e-85'): break
    return total*scale


def acos_tables():
    with localcontext() as context:
        context.prec = 90
        # Only indices0..1019 can be read by the ordinary abs(x)<=3f7e8000 branch.
        ordinary = [int(decimal_acos(Decimal(i)/1024)*(1 << 29)) for i in range(1020)]
        near = []
        for i in range(138):
            if i >= 136:
                near.append(0)
                continue
            q,r = divmod(i,8)
            delta = Decimal(16-r)*(Decimal(2)**(-11-q))
            # The embedded terminal samples flatten to4,2,1 raw ULPs below1.
            # This regenerates the constants; historical generator source is unavailable.
            if i >= 120:
                delta = Decimal(2)**(-24+(2 if i<124 else 1 if i<128 else 0))
            rounded = struct.unpack('<f',struct.pack('<f',float(decimal_acos(1-delta))))[0]
            near.append(min(int(rounded*(1 << 34)),0x7fffffff))
        return ordinary,near


def main():
    table = sine_table()
    digest = hashlib.sha256(struct.pack('<1025I', *table)).hexdigest()
    assert digest == 'd95c108b1a139a3ecefc82d2acf4cad355aba1d1e711786d1408f574bbeefa33'
    lines = ['/* Generated by tools/ghidra/generate_wc3_math_tables.py; do not edit.',
             ' * floor(sin(i*pi/2048)*2^31), with the positive endpoint saturated.',
             ' * Retail quarter-wave SHA256: ' + digest + ' */',
             '#ifndef BZ_WC3_MATH_TABLES_H', '#define BZ_WC3_MATH_TABLES_H',
             'static uint32_t const wc3_sines[1025] = {']
    lines += ['    ' + ', '.join(f'0x{n:08x}u' for n in table[i:i+8]) + ',' for i in range(0,len(table),8)]
    lines += ['};', '#endif', '']
    reciprocal = reciprocal_table()
    reciprocal_hash = hashlib.sha256(struct.pack('<1025I', *reciprocal)).hexdigest()
    assert reciprocal_hash == '00217ccf4688f6710bf65f677a8f4a81e535ab86997bcdbb2ce76c49265269b1'
    lines[-2:-2] = ['/* floor(2^47/(2^23+i*2^13-1))-2^23, saturated to2^23; SHA256 ' + reciprocal_hash + ' */',
                    'static uint32_t const wc3_recips[1025] = {'] + [
        '    ' + ', '.join(f'0x{n:08x}u' for n in reciprocal[i:i+8]) + ',' for i in range(0,len(reciprocal),8)] + ['};']
    for name,table,curve_hash in zip(('wc3_acos_curve','wc3_acos_near'),acos_tables(),
            ('6233bffc73eddcf2745dc016610dbf5f818dc8ccee3305a86b062b3b670958d3',
             '6c9cb49399630fc9cecb91b57c3ff779c60e77563048017f3086bbcc7dec56a2')):
        assert hashlib.sha256(struct.pack('<%dI'%len(table),*table)).hexdigest() == curve_hash
        lines[-2:-2] = ['/* Independently reconstructed acos curve; SHA256 ' + curve_hash + ' */',
                        'static uint32_t const ' + name + '[' + str(len(table)) + '] = {'] + [
            '    ' + ', '.join(f'0x{n:08x}u' for n in table[i:i+8]) + ',' for i in range(0,len(table),8)] + ['};']
    (ROOT / 'games/warcraft-3/common/wc3_math_tables.h').write_text('\n'.join(lines))
    print(digest)


if __name__ == '__main__':
    main()
