#!/usr/bin/env python3
"""Exact retail point-range predicate, including mover lookup and prediction.

Full 05b440 calls; no stubs. Models reuse independently verified numeric bits.
"""
import argparse
import hashlib
import itertools
import json
import struct
from pathlib import Path
from verify_wc3_pathing_numeric import bits, add, subtract, multiply, MASK, SIGN


def value(word):
    return struct.unpack('<f', struct.pack('<I',word))[0]


def world_scale(word):
    # Original exponent subtraction (/32), guarded by sign-crossing at /64.
    return 0 if ((word ^ ((word-0x3000000)&MASK)) & SIGN) else (word-0x2800000)&MASK


def squared_distance(first, second):
    # 070850 inlines second-first arithmetic, then drops signs before squaring.
    delta = [subtract(b,a) for a,b in zip(first,second)]
    return add(multiply(delta[0],delta[0]),multiply(delta[1],delta[1]))


def object_header(rows):
    def pair(words):return '{'+','.join(f'0x{word:08x}u' for word in words)+'}'
    lines=['/* Generated by verify_wc3_pathing_range.py from complete original05b580 calls. */',
        'static struct { uint32_t point[2][2],velocity[2][2],old[2],radius[2],reach;',
        '    bool predict,same,accepted; } const retail_range184[] = {']
    for row in rows:
        lines.append('    {'+','.join(['{'+','.join(map(pair,row['position']))+'}',
            '{'+','.join(map(pair,row['velocity']))+'}',pair(row['old']),pair(row['radius']),
            f"0x{row['reach']:08x}u",str(row['predict']),str(int(row['same'])),
            str(row['accepted'])])+'},')
    return '\n'.join(lines+['};',''])


def check_object_export(fixture,header,expected):
    if json.loads(fixture.read_text())!=expected:
        raise ValueError('Object fixture differs from fresh original execution')
    if header.read_text()!=object_header(expected['cases']):
        raise ValueError('Engine header differs from fresh original execution')


def main():
    from unicorn import Uc, UC_ARCH_X86, UC_MODE_32, UC_HOOK_CODE
    from unicorn.x86_const import (UC_X86_REG_ESP, UC_X86_REG_EIP, UC_X86_REG_ECX,
        UC_X86_REG_EAX, UC_X86_REG_EBP, UC_X86_REG_EBX, UC_X86_REG_ESI, UC_X86_REG_EDI)
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--binary',required=True,type=Path)
    parser.add_argument('--report',required=True,type=Path)
    parser.add_argument('--object-fixture',type=Path,
                        help='Export actual original object results for the engine regression')
    parser.add_argument('--object-header',type=Path,
                        help='Export the same domain-zero cases as a C fixture')
    parser.add_argument('--check-object-fixture',type=Path)
    parser.add_argument('--check-object-header',type=Path)
    args=parser.parse_args()
    if bool(args.check_object_fixture)!=bool(args.check_object_header):
        parser.error('both checked object exports are required')
    binary=args.binary.read_bytes()
    digest=hashlib.sha256(binary).hexdigest()
    if digest != 'd51e5680243fc90e19c9d6074f7fac433c466d3cf5f46e2364291725574d8236':
        parser.error('requires retail 1.27.1.7085 game.dll')
    pe=struct.unpack_from('<I',binary,60)[0]; opt=pe+24
    base,size=[struct.unpack_from('<I',binary,opt+n)[0] for n in (28,56)]
    uc=Uc(UC_ARCH_X86,UC_MODE_32)
    uc.mem_map(base,(size+4095)&~4095)
    uc.mem_write(base,binary[:struct.unpack_from('<I',binary,opt+60)[0]])
    for i in range(struct.unpack_from('<H',binary,pe+6)[0]):
        s=opt+struct.unpack_from('<H',binary,pe+20)[0]+40*i
        va,count,offset=struct.unpack_from('<III',binary,s+12)
        if count: uc.mem_write(base+va,binary[offset:offset+count])
    uc.mem_map(0x10000000,0x10000); uc.mem_map(0x20000000,0x10000)
    stack,stop=0x20008000,0x30000000
    registry,slots,mover,bridge,game,owner,inputs=[0x10000000+n for n in [0,0x100,0x200,0x400,0x600,0x800,0x1000]]
    def write(address,*words):
        uc.mem_write(address,struct.pack('<'+'I'*len(words),*(w&MASK for w in words)))
    def read(address):
        return struct.unpack('<I',uc.mem_read(address,4))[0]
    write(0x6fd68610,registry);write(registry+0xc,slots);write(registry+0x1c,1)
    write(slots,-2,mover);write(mover+0x14,0,100);write(bridge+8,0,100)
    write(0x6fd3c82c,game);write(0x6fd53a48,owner)
    write(0x6fd3c740,bits(-1),0,bits(1),bits(2))
    epsilon=read(0x6fcd53a0);time_epsilon=read(0x6fcd539c)
    observed=[]
    def observe(machine,address,size,data):
        frame=machine.reg_read(UC_X86_REG_EBP)
        observed.append((read(frame-8),read(frame+0x10)))
    uc.hook_add(UC_HOOK_CODE,observe,begin=0x6f05b52f,end=0x6f05b52f)
    preserved=[UC_X86_REG_EBX,UC_X86_REG_ESI,UC_X86_REG_EDI,UC_X86_REG_EBP]
    counts={'ordinary':0,'adjacent_boundary':0,'prediction':0,'conversion_guard':0}
    results={0:0,1:0}; witnesses=[]
    def check(category,origin,position,velocity,now,old,epoch,radius,reach,target,predict):
        ox,oy=map(bits,origin);px,py=map(bits,position);vx,vy=map(bits,velocity)
        write(game+0x6c,ox,oy)
        write(mover+0x70,bits(old),0,px,py,vx,vy)
        write(mover+0x90,bits(radius))
        write(owner+0x14+0x40,bits(now),epoch,bits(8))
        write(inputs,reach,*target)
        prior=[bytes(uc.mem_read(a,n)) for a,n in [(mover,0x100),(game,0x100),(inputs,12),(bridge,16),(registry,0x100),(owner,0x100)]]
        elapsed=subtract(bits(now),bits(old))
        if (elapsed & ~SIGN)<time_epsilon: elapsed=0
        elapsed=add(elapsed,bits(epoch*8))
        center=[px,py] if not predict else [add(p,multiply(v,elapsed)) for p,v in zip([px,py],[vx,vy])]
        local=[world_scale(subtract(t,o)) for t,o in zip(target,[ox,oy])]
        effective=add(world_scale(reach),bits(radius))
        limit=multiply(effective,effective)
        distance=squared_distance(local,center)
        expected=int(value(limit)>value(distance) or value(epsilon)>value(subtract(distance,limit)&~SIGN))
        write(stack,stop,inputs,inputs+4,inputs+8,predict)
        uc.reg_write(UC_X86_REG_ESP,stack);uc.reg_write(UC_X86_REG_ECX,bridge)
        for i,r in enumerate(preserved): uc.reg_write(r,0x11220000+i)
        observed.clear()
        uc.emu_start(0x6f05b440,stop,count=100000)
        assert uc.reg_read(UC_X86_REG_EIP)==stop
        assert uc.reg_read(UC_X86_REG_ESP)==stack+20
        assert [uc.reg_read(r) for r in preserved]==[0x11220000+i for i in range(4)]
        assert observed==[(limit,distance)],(category,origin,position,velocity,now,old,epoch,radius,hex(reach),target,predict,observed,(hex(limit),hex(distance)))
        actual=uc.reg_read(UC_X86_REG_EAX)
        assert actual==expected
        assert prior==[bytes(uc.mem_read(a,n)) for a,n in [(mover,0x100),(game,0x100),(inputs,12),(bridge,16),(registry,0x100),(owner,0x100)]]
        counts[category]+=1;results[actual]+=1
        return actual,limit,distance
    for origin,position,radius,reach,direction,factor in itertools.product(
            [(0,0),(-4096,-3072),(1024,2048)],[(0,0),(8.999,11.001)],
            [0,.25,.499,.5,.75,1.25,1.75],[0,16,32,64,128],
            [(1,0),(0,-1),(.6,.8),(-.8,.6)],[0,.5,1,1.001,1.5]):
        extent=(radius+reach/32)*factor
        target=tuple(bits(o+32*(p+d*extent)) for o,p,d in zip(origin,position,direction))
        check('ordinary',origin,position,(0,0),0,0,0,radius,bits(reach),target,0)
    # Find model transition near each positive-axis radius, then execute adjacent
    # original float inputs. Bracket includes the squared-distance tolerance.
    for radius,reach in itertools.product([0,.25,.499,.5,.75,1.25,1.75],[0,16,32,64,128]):
        effective=add(world_scale(bits(reach)),bits(radius));limit=multiply(effective,effective)
        lo=bits(max(0,(radius+reach/32)*32-1));hi=bits((radius+reach/32)*32+2)
        def accepted(x):
            dx=world_scale(x);distance=multiply(dx,dx)
            return value(limit)>value(distance) or value(epsilon)>value(subtract(distance,limit)&~SIGN)
        assert accepted(lo) and not accepted(hi),(radius,reach,value(epsilon),value(lo),value(hi),accepted(lo),accepted(hi))
        while hi-lo>1:
            mid=(lo+hi)//2
            if accepted(mid):lo=mid
            else:hi=mid
        for x in [max(0,lo-1),lo,hi,hi+1]:
            actual,lim,dist=check('adjacent_boundary',(0,0),(0,0),(0,0),0,0,0,radius,bits(reach),(x,0),0)
            if x in [lo,hi] and len(witnesses)<12:
                witnesses.append(dict(radius=radius,reach=reach,x_bits=hex(x),limit_bits=hex(lim),distance_bits=hex(dist),accepted=actual))
    for origin,velocity,now,old,epoch,predict,target_delta in itertools.product(
            [(0,0),(-4096,2048)],[(.125,0),(-.25,.5),(.499,-.125)],
            [0,.125,.5],[0,.125],[0,1],[0,1],[(0,0),(.5,0),(1,1),(-2,3)]):
        position=(8.999,11.001)
        target=tuple(bits(o+32*(p+d)) for o,p,d in zip(origin,position,target_delta))
        check('prediction',origin,position,velocity,now,old,epoch,.499,bits(16),target,predict)
    for reach in [0,1,0x2ffffff,0x3000000,0x3000001,0x80000000,0x82ffffff,0x83000000,0x83000001]:
        for target in [(0,0),(reach,0),(0,reach)]:
            check('conversion_guard',(0,0),(0,0),(0,0),0,0,0,.5,reach,target,0)
    # Same order target: stored center is outside, elapsed-velocity prediction
    # is inside. The original predicate must leave both clocks/positions intact.
    prediction_witness=[]
    for predict in [0,1]:
        actual,limit,distance=check('prediction',(0,0),(0,0),(.5,0),1,0,0,
            .25,bits(0),(bits(16),0),predict)
        assert actual==predict
        prediction_witness.append(dict(predict=predict,accepted=actual,
            radius_squared_bits=hex(limit),distance_squared_bits=hex(distance)))
    for sign,offset in itertools.product([0,SIGN],[-1,0,1]):
        now=value((time_epsilon+offset)|sign)
        for predict in [0,1]:
            check('prediction',(0,0),(0,0),(1,-1),now,0,0,.25,bits(0),
                (bits(.01),bits(-.01)),predict)
    # Sibling object predicate: both radii and both independently predicted
    # centers; no world-origin conversion, plus an authored minimum radius.
    target_mover,target_bridge,negative_slots=0x10001200,0x10001400,0x10001600
    minimum_radius=read(0x6fcd53f0)
    write(registry+0x1c,2);write(registry+0x2c,negative_slots);write(registry+0x3c,2)
    write(slots,-2,mover,-2,target_mover)
    write(negative_slots,-2,mover,-2,target_mover)
    write(mover,0x6fa9129c);write(target_mover,0x6fa9129c)
    object_observed=[]
    def observe_object(machine,address,size,data):
        frame=machine.reg_read(UC_X86_REG_EBP)
        object_observed.append((read(frame-4),read(frame+0x10)))
    uc.hook_add(UC_HOOK_CODE,observe_object,begin=0x6f05b671,end=0x6f05b671)
    object_counts={'ordinary':0,'adjacent_boundary':0,'prediction':0,'same_identity':0,'minimum_clamp':0}
    object_rows=[];spell_wrapper_cases=0
    source_unit,target_unit=0x10002000,0x10002400
    write(source_unit,0x6fb77eb0);write(target_unit,0x6fb77eb0)
    def check_object(category,source_position,target_position,source_radius,target_radius,
                     reach,predict=0,source_velocity=(0,0),target_velocity=(0,0),
                     old_times=(0,0),domains=(0,0),same=False):
        nonlocal spell_wrapper_cases
        raw_indices=[domains[0],domains[1]|1]
        for address,host,index,generation,position,velocity,old,radius in zip(
                [mover,target_mover],[bridge,target_bridge],raw_indices,[100,101],
                [source_position,target_position],[source_velocity,target_velocity],old_times,
                [source_radius,target_radius]):
            write(address+0x14,index,generation)
            write(host+8,index,generation)
            write(address+0x70,bits(old),0,*position,*map(bits,velocity))
            write(address+0x90,radius)
        write(owner+0x14+0x40,bits(1),0,bits(8))
        write(owner+0x68+0x40,bits(.5),0,bits(8))
        if same:
            write(target_bridge+8,*[read(bridge+n) for n in [8,12]])
            target_position=source_position;target_radius=source_radius
            target_velocity=source_velocity;old_times=(old_times[0],old_times[0]);domains=(domains[0],domains[0])
        centers=[]
        for position,velocity,old,domain in zip([source_position,target_position],
                [source_velocity,target_velocity],old_times,domains):
            elapsed=subtract(bits(.5 if domain else 1),bits(old))
            if elapsed&~SIGN<time_epsilon:elapsed=0
            centers.append(position if not predict else tuple(
                add(p,multiply(bits(v),elapsed)) for p,v in zip(position,velocity)))
        effective=add(add(world_scale(reach),target_radius),source_radius)
        effective=max(effective,minimum_radius) # finite nonnegative corpus
        limit=multiply(effective,effective)
        distance=squared_distance(centers[1],centers[0])
        expected=int(value(limit)>value(distance) or value(epsilon)>value(subtract(distance,limit)&~SIGN))
        write(inputs,reach)
        watched=[(mover,0x100),(target_mover,0x100),(bridge,16),(target_bridge,16),
                 (registry,0x100),(owner,0x100),(game,0x100),(inputs,4)]
        before=[bytes(uc.mem_read(a,n)) for a,n in watched]
        write(stack,stop,inputs,target_bridge,predict)
        uc.reg_write(UC_X86_REG_ESP,stack);uc.reg_write(UC_X86_REG_ECX,bridge)
        for i,r in enumerate(preserved):uc.reg_write(r,0x11220000+i)
        object_observed.clear()
        uc.emu_start(0x6f05b580,stop,count=100000)
        assert uc.reg_read(UC_X86_REG_EIP)==stop
        assert uc.reg_read(UC_X86_REG_ESP)==stack+16
        assert [uc.reg_read(r) for r in preserved]==[0x11220000+i for i in range(4)]
        assert object_observed==[(limit,distance)],(category,source_position,target_position,source_radius,target_radius,hex(reach),predict,object_observed,(hex(limit),hex(distance)))
        actual=uc.reg_read(UC_X86_REG_EAX)
        assert actual==expected
        assert before==[bytes(uc.mem_read(a,n)) for a,n in watched]
        object_counts[category]+=1
        # OpenRealm owns one movement clock. Keep other native clock domains in
        # the full oracle, but export only inputs representable by that clock.
        if domains==(0,0):
            object_rows.append(dict(category=category,
                position=[list(source_position),list(target_position)],
                velocity=[list(map(bits,source_velocity)),list(map(bits,target_velocity))],
                old=list(map(bits,old_times)),radius=[source_radius,target_radius],
                reach=reach,predict=predict,same=same,accepted=actual,
                limit=object_observed[0][0],distance=object_observed[0][1]))
            if predict or (source_velocity==(0,0) and target_velocity==(0,0)):
                # Complete shared-spell caller41d1f0 and authentic CUnit
                # vtable+b8 getter6864d0. The target has no perimeter record:
                # the original fallback68c250/05ac80 naturally returns zero.
                write(source_unit+0x16c,*[read(bridge+n) for n in (8,12)])
                write(target_unit+0x16c,*[read(target_bridge+n) for n in (8,12)])
                unit_before=[bytes(uc.mem_read(p,0x300)) for p in (source_unit,target_unit)]
                write(stack,stop,inputs,source_unit if same else target_unit)
                uc.reg_write(UC_X86_REG_ESP,stack);uc.reg_write(UC_X86_REG_ECX,source_unit)
                for i,r in enumerate(preserved):uc.reg_write(r,0x11220000+i)
                object_observed.clear()
                uc.emu_start(0x6f41d1f0,stop,count=100000)
                assert uc.reg_read(UC_X86_REG_EIP)==stop
                assert uc.reg_read(UC_X86_REG_ESP)==stack+12
                assert [uc.reg_read(r) for r in preserved]==[0x11220000+i for i in range(4)]
                assert uc.reg_read(UC_X86_REG_EAX)==actual
                assert object_observed==[(limit,distance)]
                assert before==[bytes(uc.mem_read(a,n)) for a,n in watched]
                assert unit_before==[bytes(uc.mem_read(p,0x300)) for p in (source_unit,target_unit)]
                spell_wrapper_cases+=1
        return actual,limit,distance
    for sr,tr,reach,direction,factor in itertools.product(
            [0,.125,.499,.5,1.25],[0,.125,.5,1.75],[0,16,64],
            [(1,0),(-.6,.8)],[0,.5,1,1.001,2]):
        extent=max(value(minimum_radius),sr+tr+reach/32)*factor
        target=tuple(bits(d*extent) for d in direction)
        check_object('ordinary',(0,0),target,bits(sr),bits(tr),bits(reach))
    for sr,tr,reach in itertools.product([0,.125,.5,1.25],[0,.125,.5],[0,16,64]):
        effective=max(add(add(world_scale(bits(reach)),bits(tr)),bits(sr)),minimum_radius)
        limit=multiply(effective,effective)
        lo=bits(max(0,value(effective)-.1));hi=bits(value(effective)+.1)
        def object_accept(x):
            distance=multiply(x,x)
            return value(limit)>value(distance) or value(epsilon)>value(subtract(distance,limit)&~SIGN)
        assert object_accept(lo) and not object_accept(hi)
        while hi-lo>1:
            mid=(lo+hi)//2
            if object_accept(mid):lo=mid
            else:hi=mid
        for x in [lo-1,lo,hi,hi+1]:
            check_object('adjacent_boundary',(0,0),(x,0),bits(sr),bits(tr),bits(reach))
    for domains,velocity_pair,old_times,predict,target in itertools.product(
            [(0,0),(0,SIGN),(SIGN,0),(SIGN,SIGN)],
            [((.5,0),(0,0)),((0,0),(-.5,0)),((.5,.25),(-.25,-.125))],
            [(0,0),(.125,.25)],[0,1],[(1,0),(.5,.5),(4,2)]):
        check_object('prediction',tuple(map(bits,(0,0))),tuple(map(bits,target)),bits(.125),bits(.125),
            bits(0),predict,*velocity_pair,old_times,domains)
    for radius,reach,predict,domain in itertools.product([0,.499,1.75],[0,16,64],[0,1],[0,SIGN]):
        assert check_object('same_identity',tuple(map(bits,(8.999,11.001))),tuple(map(bits,(99,99))),
            bits(radius),bits(0),bits(reach),predict,(.499,-.125),(0,0),(.125,0),(domain,0),True)[0]==1
    object_clamp_witness=[]
    for side,radius,position in itertools.product([0,1],
            [minimum_radius-1,minimum_radius,minimum_radius+1],
            [minimum_radius-1,minimum_radius,minimum_radius+1,bits(.5)]):
        radii=[0,0];radii[side]=radius
        actual,limit,distance=check_object('minimum_clamp',(0,0),(position,0),*radii,bits(0))
        if side==0 and position==minimum_radius:
            object_clamp_witness.append(dict(source_radius_bits=hex(radius),
                radius_squared_bits=hex(limit),distance_squared_bits=hex(distance),accepted=actual))
    # The helper has no null-result guard after its resolver. Invalid handles
    # are caller precondition failures, not a false result. Verify expected
    # unmapped dereference without patching the null page or original code.
    from unicorn import UcError, UC_ERR_READ_UNMAPPED
    identity_faults=[]
    for invalid_side,kind in itertools.product(['source','target'],['generation','free_slot','out_of_bounds']):
        write(mover+0x14,0,100);write(target_mover+0x14,1,101)
        write(bridge+8,0,100);write(target_bridge+8,1,101)
        write(slots,-2,mover,-2,target_mover)
        host=bridge if invalid_side=='source' else target_bridge
        index=0 if invalid_side=='source' else 1
        if kind=='generation':write(host+12,999)
        elif kind=='free_slot':write(slots+index*8,-1)
        else:write(host+8,2)
        write(stack,stop,inputs,target_bridge,0)
        uc.reg_write(UC_X86_REG_ESP,stack);uc.reg_write(UC_X86_REG_ECX,bridge)
        try:
            uc.emu_start(0x6f05b580,stop,count=100000)
        except UcError as error:
            assert error.errno==UC_ERR_READ_UNMAPPED
            assert uc.reg_read(UC_X86_REG_EIP)==(0x6f05b5e5 if invalid_side=='source' else 0x6f05b5c8)
            identity_faults.append(dict(side=invalid_side,kind=kind,eip=hex(uc.reg_read(UC_X86_REG_EIP))))
        else:
            raise AssertionError('Invalid handle unexpectedly returned')
    report=dict(passed=True,binary_sha256=digest,entry='6f05b440',cases=counts,results=results,
        prediction_witness=prediction_witness, time_deadzone_bits=hex(time_epsilon),
        object_cases=object_counts,object_clamp_witness=object_clamp_witness,object_minimum_radius_bits=hex(minimum_radius),object_minimum_radius=value(minimum_radius),
        object_identity_faults=identity_faults,
        object_contract='max(minimum radius, retail_add(retail_add(requested range/32,target radius),source radius)); predict resolves both clocks independently; same squared-distance tolerance as point predicate; no self exclusion or invalid-handle guard',
        epsilon_bits=hex(epsilon),epsilon=value(epsilon),boundary_witnesses=witnesses,
        contract='world target minus game origin, guarded exponent /32; effective radius=converted requested range+mover radius; second-first squared distance; accepted if limit>distance OR abs(retail_subtract(distance,limit))<epsilon; predict uses original clock and velocity with no state writes',
        assertions=['exact squared radius and squared distance at original return from070850','boolean result','callee-saved registers and stack','unchanged mover, game, registry, bridge, input and owner bytes'],
        exclusions=['Point predicate invalid/stale mover handles; object faults covered separately','Nonfinite producer inputs','Point predicate clock domain1; epoch wrap in both predicates','Object predicate nonfinite inputs and upstream handle validation','Full order dispatch composition'])
    exported=dict(binary_sha256=digest,entry='6f05b580',now=bits(1),cases=object_rows)
    if args.object_fixture:
        args.object_fixture.parent.mkdir(parents=True,exist_ok=True)
        args.object_fixture.write_text(json.dumps(exported,indent=2)+'\n')
    if args.object_header:
        args.object_header.parent.mkdir(parents=True,exist_ok=True)
        args.object_header.write_text(object_header(object_rows))
    if args.check_object_fixture:
        check_object_export(args.check_object_fixture,args.check_object_header,exported)
        report['engine_exports_verified']=True
    report['engine_object_cases']=len(object_rows)
    report['spell_wrapper_cases']=spell_wrapper_cases
    report['spell_wrapper_contract']='Complete41d1f0 calls authentic vtable+b8 getter6864d0 and predicts both movers via05b580; out-of-range68c250/05ac80 returns zero for absent target perimeter. Perimeter-present fallback and full spell approach completion are excluded.'
    args.report.parent.mkdir(parents=True,exist_ok=True)
    args.report.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))


if __name__=='__main__':main()
