/* galaxy_host.c — SC2 Galaxy scripting host for openwarcraft3.
 *
 * Registers all SC2 native functions from TriggerLibs/natives.galaxy so that
 * Galaxy scripts can execute without a full SC2 engine.  Functions that are
 * not yet implemented forward to galaxy_stub() which returns null.
 *
 * To add a real implementation: replace galaxy_stub with a function that
 * uses jass_check*() to read arguments and jass_push*() to return a value.
 */

#include "../../warcraft-3/jass/jass.h"

/* Generic no-op stub — returns null, zero overhead. */
static DWORD galaxy_stub(LPJASS j) {
    (void)j;
    return jass_pushnull(j);
}

/* TriggerCreate: wire a Galaxy function by name into the VM trigger system. */
static DWORD sc2_TriggerCreate(LPJASS j) {
    LPCSTR name = jass_checkstring(j, 1);
    if (name) jass_startcoroutinebyname(j, name);
    return jass_pushnull(j);
}

/* Wait: delegate to jass_sleep; arg is seconds (fixed-point), VM uses ms. */
static DWORD sc2_Wait(LPJASS j) {
    FLOAT secs = jass_checknumber(j, 1);
    jass_sleep(j, (DWORD)(secs * 1000.0f));
    return 0;
}

static JASSMODULE sc2_galaxy_natives[] = {
    { "ACos", galaxy_stub },
    { "ASin", galaxy_stub },
    { "ATan", galaxy_stub },
    { "ATan2", galaxy_stub },
    { "AbilityClass", galaxy_stub },
    { "AbsF", galaxy_stub },
    { "AchievementAward", galaxy_stub },
    { "AchievementErase", galaxy_stub },
    { "AchievementPanelSetCategory", galaxy_stub },
    { "AchievementPanelSetVisible", galaxy_stub },
    { "AchievementPercentText", galaxy_stub },
    { "AchievementTermQuantitySet", galaxy_stub },
    { "AchievementsDisable", galaxy_stub },
    { "AngleBetweenPoints", galaxy_stub },
    { "CatalogEntryClass", galaxy_stub },
    { "CatalogEntryCount", galaxy_stub },
    { "CatalogEntryGet", galaxy_stub },
    { "CatalogEntryIsValid", galaxy_stub },
    { "CatalogEntryParent", galaxy_stub },
    { "CatalogEntryScope", galaxy_stub },
    { "CatalogFieldCount", galaxy_stub },
    { "CatalogFieldGet", galaxy_stub },
    { "CatalogFieldIsArray", galaxy_stub },
    { "CatalogFieldIsScope", galaxy_stub },
    { "CatalogFieldType", galaxy_stub },
    { "CatalogFieldValueCount", galaxy_stub },
    { "CatalogFieldValueGet", galaxy_stub },
    { "CatalogFieldValueSet", galaxy_stub },
    { "CinematicDataRun", galaxy_stub },
    { "CinematicDataStop", galaxy_stub },
    { "CinematicFade", galaxy_stub },
    { "CinematicMode", galaxy_stub },
    { "CinematicOverlay", galaxy_stub },
    { "Cos", galaxy_stub },
    { "DifficultyEnabled", galaxy_stub },
    { "DifficultyName", galaxy_stub },
    { "DifficultyNameCampaign", galaxy_stub },
    { "DistanceBetweenPoints", galaxy_stub },
    { "IntLoopBegin", galaxy_stub },
    { "IntLoopDone", galaxy_stub },
    { "IntLoopEnd", galaxy_stub },
    { "IntLoopStep", galaxy_stub },
    { "MaxF", galaxy_stub },
    { "MinF", galaxy_stub },
    { "ModF", galaxy_stub },
    { "PlayerAddChargeRegen", galaxy_stub },
    { "PlayerAddChargeUsed", galaxy_stub },
    { "PlayerAddCooldown", galaxy_stub },
    { "PlayerBeaconAlert", galaxy_stub },
    { "PlayerBeaconClearTarget", galaxy_stub },
    { "PlayerBeaconGetTargetPoint", galaxy_stub },
    { "PlayerBeaconGetTargetUnit", galaxy_stub },
    { "PlayerBeaconIsAutoCast", galaxy_stub },
    { "PlayerBeaconIsFromUser", galaxy_stub },
    { "PlayerBeaconIsSet", galaxy_stub },
    { "PlayerBeaconSetAutoCast", galaxy_stub },
    { "PlayerBeaconSetTargetPoint", galaxy_stub },
    { "PlayerBeaconSetTargetUnit", galaxy_stub },
    { "PlayerCreateEffectPoint", galaxy_stub },
    { "PlayerCreateEffectUnit", galaxy_stub },
    { "PlayerGetAlliance", galaxy_stub },
    { "PlayerGetChargeRegen", galaxy_stub },
    { "PlayerGetChargeUsed", galaxy_stub },
    { "PlayerGetCooldown", galaxy_stub },
    { "PlayerGetState", galaxy_stub },
    { "PlayerGroupActive", galaxy_stub },
    { "PlayerGroupAdd", galaxy_stub },
    { "PlayerGroupAll", galaxy_stub },
    { "PlayerGroupAlliance", galaxy_stub },
    { "PlayerGroupClear", galaxy_stub },
    { "PlayerGroupCopy", galaxy_stub },
    { "PlayerGroupEmpty", galaxy_stub },
    { "PlayerGroupHasPlayer", galaxy_stub },
    { "PlayerGroupLoopBegin", galaxy_stub },
    { "PlayerGroupLoopDone", galaxy_stub },
    { "PlayerGroupLoopEnd", galaxy_stub },
    { "PlayerGroupLoopStep", galaxy_stub },
    { "PlayerGroupRemove", galaxy_stub },
    { "PlayerGroupSingle", galaxy_stub },
    { "PlayerPauseAllCharges", galaxy_stub },
    { "PlayerPauseAllCooldowns", galaxy_stub },
    { "PlayerScoreValueEnable", galaxy_stub },
    { "PlayerScoreValueEnableAll", galaxy_stub },
    { "PlayerScoreValueGetAsFixed", galaxy_stub },
    { "PlayerScoreValueGetAsInt", galaxy_stub },
    { "PlayerScoreValueSetFromFixed", galaxy_stub },
    { "PlayerScoreValueSetFromInt", galaxy_stub },
    { "PlayerSetAlliance", galaxy_stub },
    { "PlayerSetState", galaxy_stub },
    { "PlayerValidateEffectPoint", galaxy_stub },
    { "PlayerValidateEffectUnit", galaxy_stub },
    { "Point", galaxy_stub },
    { "PointFromId", galaxy_stub },
    { "PointGetFacing", galaxy_stub },
    { "PointGetHeight", galaxy_stub },
    { "PointGetX", galaxy_stub },
    { "PointGetY", galaxy_stub },
    { "PointPathingCliffLevel", galaxy_stub },
    { "PointReflect", galaxy_stub },
    { "PointWithOffset", galaxy_stub },
    { "PointWithOffsetPolar", galaxy_stub },
    { "Pow", galaxy_stub },
    { "PreloadAsset", galaxy_stub },
    { "PreloadImage", galaxy_stub },
    { "PreloadModel", galaxy_stub },
    { "PreloadMovie", galaxy_stub },
    { "PreloadObject", galaxy_stub },
    { "PreloadScene", galaxy_stub },
    { "PreloadScript", galaxy_stub },
    { "PreloadSound", galaxy_stub },
    { "RandomFixed", galaxy_stub },
    { "RandomInt", galaxy_stub },
    { "RegionAddCircle", galaxy_stub },
    { "RegionAddRect", galaxy_stub },
    { "RegionAddRegion", galaxy_stub },
    { "RegionAttachToUnit", galaxy_stub },
    { "RegionCircle", galaxy_stub },
    { "RegionContainsPoint", galaxy_stub },
    { "RegionEmpty", galaxy_stub },
    { "RegionEntireMap", galaxy_stub },
    { "RegionFromId", galaxy_stub },
    { "RegionGetAttachUnit", galaxy_stub },
    { "RegionGetBoundsMax", galaxy_stub },
    { "RegionGetBoundsMin", galaxy_stub },
    { "RegionGetCenter", galaxy_stub },
    { "RegionGetOffset", galaxy_stub },
    { "RegionPlayableMap", galaxy_stub },
    { "RegionPlayableMapSet", galaxy_stub },
    { "RegionRandomPoint", galaxy_stub },
    { "RegionRect", galaxy_stub },
    { "RegionSetCenter", galaxy_stub },
    { "Sin", galaxy_stub },
    { "SoundLink", galaxy_stub },
    { "SoundLinkAsset", galaxy_stub },
    { "SoundLinkId", galaxy_stub },
    { "SoundPlay", galaxy_stub },
    { "SoundPlayAtPoint", galaxy_stub },
    { "SoundPlayOnUnit", galaxy_stub },
    { "SoundPlayScene", galaxy_stub },
    { "SoundPlaySceneFile", galaxy_stub },
    { "SquareRoot", galaxy_stub },
    { "Tan", galaxy_stub },
    { "TriggerAddEventPlayerAIWave", galaxy_stub },
    { "TriggerAddEventPlayerAllianceChange", galaxy_stub },
    { "TriggerAddEventPlayerLeft", galaxy_stub },
    { "TriggerAddEventPlayerPropChange", galaxy_stub },
    { "TriggerAddEventTimeElapsed", galaxy_stub },
    { "TriggerAddEventTimePeriodic", galaxy_stub },
    { "TriggerAddEventTimer", galaxy_stub },
    { "UnitClearInfoText", galaxy_stub },
    { "UnitCreate", galaxy_stub },
    { "UnitFilter", galaxy_stub },
    { "UnitFilterMatch", galaxy_stub },
    { "UnitFilterSetState", galaxy_stub },
    { "UnitFilterStr", galaxy_stub },
    { "UnitForceStatusBar", galaxy_stub },
    { "UnitFromId", galaxy_stub },
    { "UnitGetAttachmentPoint", galaxy_stub },
    { "UnitGetFacing", galaxy_stub },
    { "UnitGetHeight", galaxy_stub },
    { "UnitGetPosition", galaxy_stub },
    { "UnitGetType", galaxy_stub },
    { "UnitGroup", galaxy_stub },
    { "UnitGroupAdd", galaxy_stub },
    { "UnitGroupAlliance", galaxy_stub },
    { "UnitGroupClear", galaxy_stub },
    { "UnitGroupCopy", galaxy_stub },
    { "UnitGroupEmpty", galaxy_stub },
    { "UnitGroupFilter", galaxy_stub },
    { "UnitGroupFilterAlliance", galaxy_stub },
    { "UnitGroupFilterPlane", galaxy_stub },
    { "UnitGroupFilterPlayer", galaxy_stub },
    { "UnitGroupFilterRegion", galaxy_stub },
    { "UnitGroupFilterThreat", galaxy_stub },
    { "UnitGroupFromId", galaxy_stub },
    { "UnitGroupHasUnit", galaxy_stub },
    { "UnitGroupIdle", galaxy_stub },
    { "UnitGroupIssueOrder", galaxy_stub },
    { "UnitGroupLoopBegin", galaxy_stub },
    { "UnitGroupLoopCurrent", galaxy_stub },
    { "UnitGroupLoopDone", galaxy_stub },
    { "UnitGroupLoopEnd", galaxy_stub },
    { "UnitGroupLoopStep", galaxy_stub },
    { "UnitGroupNearestUnit", galaxy_stub },
    { "UnitGroupRandomUnit", galaxy_stub },
    { "UnitGroupRemove", galaxy_stub },
    { "UnitGroupTestPlane", galaxy_stub },
    { "UnitGroupUnit", galaxy_stub },
    { "UnitGroupWaitUntilIdle", galaxy_stub },
    { "UnitInventoryGroup", galaxy_stub },
    { "UnitIsAlive", galaxy_stub },
    { "UnitIsValid", galaxy_stub },
    { "UnitKill", galaxy_stub },
    { "UnitLastCreated", galaxy_stub },
    { "UnitLastCreatedGroup", galaxy_stub },
    { "UnitLoadModel", galaxy_stub },
    { "UnitPauseAll", galaxy_stub },
    { "UnitRefFromUnit", galaxy_stub },
    { "UnitRefFromVariable", galaxy_stub },
    { "UnitRefToUnit", galaxy_stub },
    { "UnitRemove", galaxy_stub },
    { "UnitRevive", galaxy_stub },
    { "UnitSetCursor", galaxy_stub },
    { "UnitSetHeight", galaxy_stub },
    { "UnitSetInfoText", galaxy_stub },
    { "UnitSetScale", galaxy_stub },
    { "UnitSetState", galaxy_stub },
    { "UnitTechTreeBehaviorCount", galaxy_stub },
    { "UnitTechTreeUnitCount", galaxy_stub },
    { "UnitTechTreeUpgradeCount", galaxy_stub },
    { "UnitTestState", galaxy_stub },
    { "UnitTypeAnimationLoad", galaxy_stub },
    { "UnitTypeAnimationUnload", galaxy_stub },
    { "UnitTypeFromString", galaxy_stub },
    { "UnitTypeGetCost", galaxy_stub },
    { "UnitTypeGetName", galaxy_stub },
    { "UnitTypeGetProperty", galaxy_stub },
    { "UnitTypeIsAffectedByUpgrade", galaxy_stub },
    { "UnitTypeTestAttribute", galaxy_stub },
    { "UnitTypeTestFlag", galaxy_stub },
    { "UnitUnloadModel", galaxy_stub },
    { "UnitWaitUntilIdle", galaxy_stub },
    { "VisRevealerCreate", galaxy_stub },
    { "VisRevealerLastCreated", galaxy_stub },
    { NULL, NULL },
};

/* Return the SC2 native table; pass as host.galaxy_natives. */
LPCJASSMODULE galaxy_get_natives(void) {
    return sc2_galaxy_natives;
}
