// Read-only UI request affinity and recursive physical group membership.
let installed=false,recording=true,started=false,dispatch=0,count=0,depth=0,tick=0;
function install(m){
 if(installed||m.name.toLowerCase()!=='game.dll')return;
 const base=m.base,pe=base.add(base.add(0x3c).readU32());
 if(Process.pointerSize!==4||pe.add(8).readU32()!==config.timestamp||pe.add(80).readU32()!==config.imageSize)throw Error('PE differs');
 installed=true;send({event:'module',base:base.toString(),path:m.path});
 const resolve=(id)=>{const reg=base.add(0xd68610).readPointer(),negative=!!(id[0]&0x80000000),index=id[0]&0x7fffffff;if(index>=reg.add(negative?0x3c:0x1c).readU32())return null;const slot=reg.add(negative?0x2c:0xc).readPointer().add(index*8);if(slot.readU32()!==0xfffffffe)return null;const obj=slot.add(4).readPointer();return obj.add(0x18).readU32()===id[1]?obj:null;};
 const state=(req)=>{const rows=[];for(let i=0;i<12;i++){const id=[req.add(0x1c+12*i).readU32(),req.add(0x20+12*i).readU32()],m=resolve(id);if(m)rows.push({index:i,id,ready:req.add(0xac+4*i).readU32()!==0xffffffff,counter:m.add(0x98).readPointer().add(0x40).readU32(),group:[m.add(0x9c).readU32(),m.add(0xa0).readU32()]});}return rows;};
 for(const [rva,name]of [[0x169c50,'acquire'],[0x169d60,'release']])Interceptor.attach(base.add(rva),{onEnter(){this.take=recording&&started;if(!this.take)return;this.req=this.context.ecx;send({event:'scope',phase:name+'-enter',request:[this.req.add(0x14).readU32(),this.req.add(0x18).readU32()],rows:state(this.req)});},onLeave(){if(this.take)send({event:'scope',phase:name+'-leave',request:[this.req.add(0x14).readU32(),this.req.add(0x18).readU32()],rows:state(this.req)});}});
 const unitState=(u)=>{const mover=resolve([u.add(0x16c).readU32(),u.add(0x170).readU32()]);return {head:[u.add(0x19c).readU32(),u.add(0x1a0).readU32()],internal:[u.add(0x174).readU32(),u.add(0x178).readU32()],count:u.add(0x1b4).readU32(),group:mover?[mover.add(0x9c).readU32(),mover.add(0xa0).readU32()]:null};};
 for(const [rva,name]of [[0x67abe0,'head-dispatch'],[0x67c230,'issued-point'],[0x693490,'append']])Interceptor.attach(base.add(rva),{onEnter(args){this.take=recording&&started;if(!this.take)return;this.unit=this.context.ecx;this.order=args[0];send({event:name+'-enter',tick,unit:this.unit.toString(),command:this.order.add(0x24).readU32(),state:unitState(this.unit)});},onLeave(){if(this.take)send({event:name+'-leave',tick,unit:this.unit.toString(),state:unitState(this.unit)});}});
 Interceptor.attach(base.add(0x5ffb60),{onEnter(){if(recording&&started){const u=this.context.ecx.add(0x30).readPointer();if(!u.isNull())send({event:'point-task',tick,unit:u.toString(),state:unitState(u)});}}});
 Interceptor.attach(base.add(0x5fa950),{onEnter(){if(recording&&started)send({event:'cohort-search',tick,unit:this.context.ecx.toString(),state:unitState(this.context.ecx)});}});
 const words=(p,n)=>Array.from({length:n},(_,i)=>p.add(i*4).readU32());
 Interceptor.attach(base.add(0x231df0),{onEnter(args){if(args[0].isNull())return;const value=args[0].readCString();if(recording&&value.startsWith(config.prefix)){started=true;const hit=/tick=(\d+)/.exec(value);if(hit)tick=Number(hit[1]);send({event:'marker',value});}}});
 Interceptor.attach(base.add(0x6b9f70),{onEnter(){this.take=recording&&started;if(!this.take)return;dispatch++;send({event:'packet',words:words(this.context.ecx,12)});},onLeave(){if(this.take)dispatch--;}});
 let scoreDepth=0;
 Interceptor.attach(base.add(0x687b30),{onEnter(args){this.take=recording&&dispatch;if(!this.take)return;scoreDepth++;this.row={event:'score',unit:this.context.ecx.toString(),order:args[0].toUInt32(),point:[args[1].readU32(),args[2].readU32()]};},onLeave(value){if(!this.take)return;scoreDepth--;this.row.value=value.toUInt32();send(this.row);}});
 Interceptor.attach(base.add(0x058900),{onEnter(args){this.take=recording&&scoreDepth;if(this.take)this.out=args[0];},onLeave(){if(this.take)send({event:'score-pose',words:words(this.out,3)});}});
 Interceptor.attach(base.add(0x6ba800),{onEnter(){this.take=recording&&dispatch;if(!this.take)return;this.ctx=this.context.edx;this.old=this.ctx.add(0x38).readU32();},onLeave(){if(!this.take)return;const n=this.ctx.add(0x38).readU32();if(n===this.old)return;if(n!==this.old+1||n>12)throw Error('candidate count');const row=words(this.ctx.add(0x3c+this.old*36),9),u=ptr(row[0]);send({event:'candidate',unit:u.toString(),row,unit198:u.add(0x198).readU32(),unit1b4:u.add(0x1b4).readU32(),canonical:u.add(0xc).readU32()});}});
 Interceptor.attach(base.add(0x6b93a0),{onEnter(args){if(recording&&dispatch)send({event:'publish',unit:this.context.ecx.toString(),flags:args[0].toUInt32()});}});
 Interceptor.attach(base.add(0x6b8c10),{onEnter(){if(!recording||!dispatch)return;const u=this.context.ecx,ctx=this.context.edx;send({event:'attach',unit:u.toString(),type:u.add(0x1fc).readU32(),flags:u.add(0x5c).readU32(),forced:u.add(0x200).readU32(),mover:words(u.add(0x16c),2),requests:words(ctx,3),options:ctx.add(0x18).readU32()});}});
 Interceptor.attach(base.add(0x89c7c0),{onEnter(args){if(!recording||!dispatch)return;send({event:'retain',unit:args[0].sub(0x164).toString(),wrapper:this.context.ecx.toString(),request:words(this.context.ecx.add(8),2)});}});
 Interceptor.attach(base.add(0x89cd10),{onEnter(args){this.take=recording&&started;if(!this.take)return;this.wrapper=this.context.ecx;send({event:'ready',tick,wrapper:this.wrapper.toString(),request:words(this.wrapper.add(8),2),mover:words(args[0].add(0x14),2)});}});
 Interceptor.attach(base.add(0x16bcf0),{onEnter(){this.take=recording&&started;if(!this.take)return;this.req=this.context.ecx;send({event:'publish-ready',tick,request:words(this.req.add(0x14),2),flags:this.req.add(0x100).readU32(),slots:words(this.req.add(0xac),12)});},onLeave(value){if(this.take)send({event:'publish-ready-end',tick,request:words(this.req.add(0x14),2),result:value.toUInt32()});}});
 Interceptor.attach(base.add(0x16b7b0),{onEnter(args){this.take=recording&&started&&count<1024;if(!this.take)return;count++;this.group=args[0];this.bindDepth=depth++;const req=this.context.ecx;this.row={event:'bind',tick,depth:this.bindDepth,request:words(req.add(0x14),2),index:args[1].toUInt32(),flags:req.add(0x100).readU32()};},onLeave(){if(!this.take)return;if(--depth!==this.bindDepth)throw Error('unbalanced');const n=this.group.add(0x38).readU32(),rows=this.group.add(0x28).readPointer();if(n>12)throw Error('count');this.row.members=Array.from({length:n},(_,i)=>words(rows.add(i*44),2));send(this.row);}});
}
Process.attachModuleObserver({onAdded:install});
rpc.exports={finish(){recording=false;return {installed,dispatch,count,depth};}};
