// Read-only UI request affinity and recursive physical group membership.
let installed=false,recording=true,started=false,dispatch=0,count=0,depth=0,tick=0;
function install(m){
 if(installed||m.name.toLowerCase()!=='game.dll')return;
 const base=m.base,pe=base.add(base.add(0x3c).readU32());
 if(Process.pointerSize!==4||pe.add(8).readU32()!==config.timestamp||pe.add(80).readU32()!==config.imageSize)throw Error('PE differs');
 installed=true;send({event:'module',base:base.toString(),path:m.path});
 const words=(p,n)=>Array.from({length:n},(_,i)=>p.add(i*4).readU32());
 const clock=()=>{const o=base.add(0xd53a48).readPointer();return{counter:o.add(0x538).readU32(),clock:words(o.add(0x54),3)};};
 const route=(p,o)=>{const n=p.add(o+0x1c).readU32();if(n>4096)throw Error('route count');return Array.from({length:n},(_,i)=>words(p.add(o+0xc).readPointer().add(i*8),2));};
 const path=p=>p.isNull()?null:({dest:words(p.add(0x1c),4),fine:route(p,0x34),coarse:route(p,0x54),indices:words(p.add(0x74),10)});
 const mover=p=>p.isNull()?null:({id:words(p.add(0x14),2),clock:words(p.add(0x70),2),pose:words(p.add(0x78),6),radius:p.add(0x90).readU32(),path:path(p.add(0xa8).readPointer()),range:p.add(0xb0).readU32(),parameters:words(p.add(0xb4),3),flags:p.add(0xd8).readU32()});
 Interceptor.attach(base.add(0x22e9c0),{onEnter(args){if(!recording||started)return;const p=this.context.ecx,w=p.add(8).readU32(),h=p.add(12).readU32();if(w*h>4096)return;send({event:'texture244',dimensions:[w,h],orientation:args[1].toUInt32(),point:words(args[0],2),categories:Array.from(new Uint8Array(p.add(0x20).readPointer().readByteArray(w*h)))});}});
 const born=new Map();
 Interceptor.attach(base.add(0x15f7b0),{onEnter(args){this.take=recording&&!started;if(!this.take)return;this.m=this.context.ecx;this.before=mover(this.m);this.delta=words(args[0],2);},onLeave(){if(!this.take)return;born.set(this.m.toString(),this.m);send({event:'birth-write244',before:this.before,delta:this.delta,after:mover(this.m)});}});
 Interceptor.attach(base.add(0x231df0),{onEnter(args){if(started||args[0].isNull()||!args[0].readCString().startsWith(config.prefix))return;const fine=base.add(0xd53a48).readPointer().add(0x238).readPointer(),dims=words(fine.add(0x3c),2),cells=fine.add(0x28).readPointer();const owner=base.add(0xd53a48).readPointer();const hierarchy=Array.from({length:4},(_,k)=>{const m=owner.add(0x23c+k*4).readPointer(),d=words(m.add(0x3c),2),p=m.add(0x28).readPointer();return{dimensions:d,words:Array.from({length:d[0]*d[1]},(_,i)=>p.add(i*8+4).readU32())};});send({event:'initial244',rng:words(owner,2),hierarchy,movers:Array.from(born.values(),mover),dimensions:dims,cells:words(cells,dims[0]*dims[1])});}});
 Interceptor.attach(base.add(0x16fe20),{onEnter(args){this.take=recording&&started;if(!this.take)return;this.m=this.context.ecx;this.row={event:'motion244',tick,...clock(),before:mover(this.m),speed:args[0].readU32(),heading:args[1].readU32()};},onLeave(){if(this.take)send({...this.row,after:mover(this.m)});}});
 let hierarchyTaken=false;
 Interceptor.attach(base.add(0x16c150),{onEnter(){if(!recording||!started||hierarchyTaken)return;hierarchyTaken=true;const o=base.add(0xd53a48).readPointer();const f=o.add(0x238).readPointer(),cells=f.add(0x28).readPointer(),links=f.add(0x78).readPointer(),objects=new Map();for(let y=11;y<31;y++)for(let x=15;x<50;x++){let id=cells.add((y*128+x)*4).readU32()&0xffffff,guard=0;while(id!==0xffffff&&guard++<64){const l=links.add(id*8),head=l.readU32();if((head>>>24)<=1){const p=l.add(4).readPointer();objects.set(p.toString(),{category:p.add(0x34).readU32(),flags:p.add(0x40).readU32(),box:words(p.add(0x1c),4)});}id=head&0xffffff;}}send({event:'hierarchy244',objects:Array.from(objects.values()),...clock(),rng:words(o,2),maps:Array.from({length:4},(_,k)=>{const m=o.add(0x23c+k*4).readPointer(),d=words(m.add(0x3c),2),p=m.add(0x28).readPointer();return{dimensions:d,words:Array.from({length:d[0]*d[1]},(_,i)=>p.add(i*8+4).readU32())};})});}});
 Interceptor.attach(base.add(0x16c150),{onEnter(){this.take=recording&&started;if(!this.take)return;this.g=this.context.ecx;const n=this.g.add(0x38).readU32(),rows=this.g.add(0x28).readPointer();if(n>12)throw Error('visit count');this.row={event:'visit244',tick,...clock(),group:words(this.g.add(0x14),2),flags:this.g.add(0x80).readU32(),age:this.g.add(0x5c).readU32(),members:Array.from({length:n},(_,i)=>({flags:rows.add(i*44+0x28).readU32(),...mover(rows.add(i*44+0x14).readPointer())}))};send(this.row);}});
 let mapped=false;
 Interceptor.attach(base.add(0x231df0),{onEnter(args){if(mapped||args[0].isNull()||!args[0].readCString().startsWith(config.prefix))return;mapped=true;const o=base.add(0xd53a48).readPointer(),game=base.add(0xd3c82c).readPointer(),fine=o.add(0x238).readPointer();send({event:'world244',bounds:words(game.add(0x6c),4),dimensions:words(fine.add(0x3c),2),...clock()});}});
 Interceptor.attach(base.add(0x231df0),{onEnter(args){if(args[0].isNull())return;const value=args[0].readCString();if(recording&&value.startsWith(config.prefix)){started=true;const hit=/tick=(\d+)/.exec(value);if(hit)tick=Number(hit[1]);send({event:'marker',value});}}});
 Interceptor.attach(base.add(0x6b9f70),{onEnter(){this.take=recording&&started;if(!this.take)return;dispatch++;send({event:'packet',words:words(this.context.ecx,12),...clock()});},onLeave(){if(this.take)dispatch--;}});
 let scoreDepth=0;
 Interceptor.attach(base.add(0x687b30),{onEnter(args){this.take=recording&&dispatch;if(!this.take)return;scoreDepth++;this.row={event:'score',unit:this.context.ecx.toString(),order:args[0].toUInt32(),point:[args[1].readU32(),args[2].readU32()]};},onLeave(value){if(!this.take)return;scoreDepth--;this.row.value=value.toUInt32();send(this.row);}});
 Interceptor.attach(base.add(0x058900),{onEnter(args){this.take=recording&&scoreDepth;if(this.take)this.out=args[0];},onLeave(){if(this.take)send({event:'score-pose',words:words(this.out,3)});}});
 Interceptor.attach(base.add(0x6ba800),{onEnter(){this.take=recording&&dispatch;if(!this.take)return;this.ctx=this.context.edx;this.old=this.ctx.add(0x38).readU32();},onLeave(){if(!this.take)return;const n=this.ctx.add(0x38).readU32();if(n===this.old)return;if(n!==this.old+1||n>12)throw Error('candidate count');const row=words(this.ctx.add(0x3c+this.old*36),9),u=ptr(row[0]);send({event:'candidate',unit:u.toString(),row,unit198:u.add(0x198).readU32(),unit1b4:u.add(0x1b4).readU32(),canonical:u.add(0xc).readU32()});}});
 Interceptor.attach(base.add(0x6b93a0),{onEnter(args){if(recording&&dispatch)send({event:'publish',unit:this.context.ecx.toString(),flags:args[0].toUInt32()});}});
 Interceptor.attach(base.add(0x6b8c10),{onEnter(){if(!recording||!dispatch)return;const u=this.context.ecx,ctx=this.context.edx;send({event:'attach',unit:u.toString(),type:u.add(0x1fc).readU32(),flags:u.add(0x5c).readU32(),forced:u.add(0x200).readU32(),mover:words(u.add(0x16c),2),requests:words(ctx,3),options:ctx.add(0x18).readU32()});}});
 Interceptor.attach(base.add(0x89c7c0),{onEnter(args){if(!recording||!dispatch)return;send({event:'retain',unit:args[0].sub(0x164).toString(),wrapper:this.context.ecx.toString(),request:words(this.context.ecx.add(8),2)});}});
 Interceptor.attach(base.add(0x89cd10),{onEnter(args){this.take=recording&&started;if(!this.take)return;this.wrapper=this.context.ecx;send({event:'ready',tick,wrapper:this.wrapper.toString(),request:words(this.wrapper.add(8),2),mover:words(args[0].add(0x14),2)});}});
 Interceptor.attach(base.add(0x16bcf0),{onEnter(){this.take=recording&&started;if(!this.take)return;this.req=this.context.ecx;send({event:'publish-ready',tick,request:words(this.req.add(0x14),2),flags:this.req.add(0x100).readU32(),slots:words(this.req.add(0xac),12)});},onLeave(value){if(this.take)send({event:'publish-ready-end',tick,request:words(this.req.add(0x14),2),result:value.toUInt32()});}});
 Interceptor.attach(base.add(0x16b7b0),{onEnter(args){this.take=recording&&started&&count<1024;if(!this.take)return;count++;this.group=args[0];this.bindDepth=depth++;const req=this.context.ecx;this.row={event:'bind',tick,depth:this.bindDepth,request:words(req.add(0x14),2),index:args[1].toUInt32(),flags:req.add(0x100).readU32()};},onLeave(){if(!this.take)return;if(--depth!==this.bindDepth)throw Error('unbalanced');const n=this.group.add(0x38).readU32(),rows=this.group.add(0x28).readPointer();if(n>12)throw Error('count');this.row.members=Array.from({length:n},(_,i)=>words(rows.add(i*44),2));send(this.row);}});
}
Process.attachModuleObserver({onAdded:install});
rpc.exports={finish(){recording=false;return {installed,dispatch,count,depth};}};
