globals
 unit udg_PathProbeUnit=null
 timer udg_PathProbeTimer=null
 integer udg_PathProbeTick=0
endglobals
function PathExpressionInteger takes integer tag, integer value returns integer
 call Preload("PATHEXPR operand="+I2S(tag)+" type=integer")
 return value
endfunction
function PathExpressionReal takes integer tag, real value returns real
 call Preload("PATHEXPR operand="+I2S(tag)+" type=real")
 return value
endfunction
function PathProbeRecord takes string label returns nothing
 call Preload("PATHTRACE tick="+I2S(udg_PathProbeTick)+" label="+label+" x="+R2S(GetUnitX(udg_PathProbeUnit))+" y="+R2S(GetUnitY(udg_PathProbeUnit))+" order="+I2S(GetUnitCurrentOrder(udg_PathProbeUnit)))
endfunction
function PathProbeTick takes nothing returns nothing
 set udg_PathProbeTick=udg_PathProbeTick+1
 if udg_PathProbeTick-1-3*3==0 then
  call PathProbeRecord("before_expression_move")
  call IssuePointOrder(udg_PathProbeUnit,"move",1744.0-96.0-32.0,1776.0-128.0+64.0)
  call PathProbeRecord("after_expression_move")
 endif
 call PathProbeRecord("sample")
 if udg_PathProbeTick==300 then
  call PathProbeRecord("complete")
  call PauseTimer(udg_PathProbeTimer)
 endif
endfunction
function PathProbeInit takes nothing returns nothing
 call Preload("PATHNUM case=int_sub native=I2R")
 call I2R(100-10-5)
 call Preload("PATHNUM done=int_sub")
 call Preload("PATHNUM case=int_sub_add native=I2R")
 call I2R(100-10+5)
 call Preload("PATHNUM done=int_sub_add")
 call Preload("PATHNUM case=int_add_sub native=I2R")
 call I2R(100+10-5)
 call Preload("PATHNUM done=int_add_sub")
 call Preload("PATHNUM case=int_div native=I2R")
 call I2R(120/4/3)
 call Preload("PATHNUM done=int_div")
 call Preload("PATHNUM case=int_div_mul native=I2R")
 call I2R(9/2*2)
 call Preload("PATHNUM done=int_div_mul")
 call Preload("PATHNUM case=int_precedence native=I2R")
 call I2R(41-1-2*20)
 call Preload("PATHNUM done=int_precedence")
 call Preload("PATHNUM case=int_right_parens native=I2R")
 call I2R(100-(10-5))
 call Preload("PATHNUM done=int_right_parens")
 call Preload("PATHNUM case=int_left_parens native=I2R")
 call I2R((100-10)-5)
 call Preload("PATHNUM done=int_left_parens")
 call Preload("PATHNUM case=int_negative native=I2R")
 call I2R(-100-10-5)
 call Preload("PATHNUM done=int_negative")
 call Preload("PATHNUM case=real_sub native=R2I")
 call R2I(100.0-10.0-5.0)
 call Preload("PATHNUM done=real_sub")
 call Preload("PATHNUM case=real_sub_add native=R2I")
 call R2I(100.0-10.0+5.0)
 call Preload("PATHNUM done=real_sub_add")
 call Preload("PATHNUM case=real_div native=R2I")
 call R2I(120.0/4.0/3.0)
 call Preload("PATHNUM done=real_div")
 call Preload("PATHNUM case=real_div_mul native=R2I")
 call R2I(9.0/2.0*2.0)
 call Preload("PATHNUM done=real_div_mul")
 call Preload("PATHNUM case=mixed_div native=R2I")
 call R2I(120.0/4/3.0)
 call Preload("PATHNUM done=mixed_div")
 call Preload("PATHNUM case=mixed_sub native=R2I")
 call R2I(100.0-10-5.0)
 call Preload("PATHNUM done=mixed_sub")
 call Preload("PATHNUM case=real_right_parens native=R2I")
 call R2I(100.0-(10.0-5.0))
 call Preload("PATHNUM done=real_right_parens")
 call Preload("PATHNUM case=int_operands native=I2R")
 call I2R(PathExpressionInteger(1,100)-PathExpressionInteger(2,10)-PathExpressionInteger(3,5))
 call Preload("PATHNUM done=int_operands")
 call Preload("PATHNUM case=real_operands native=R2I")
 call R2I(PathExpressionReal(1,120.0)/PathExpressionReal(2,4.0)/PathExpressionReal(3,3.0))
 call Preload("PATHNUM done=real_operands")
 call Preload("PATHNUM case=mixed_operands native=R2I")
 call R2I(PathExpressionReal(1,100.0)-PathExpressionReal(2,4.0)*PathExpressionReal(3,3.0)-PathExpressionReal(4,5.0))
 call Preload("PATHNUM done=mixed_operands")
 call Preload("PATHNUM case=real_cancel native=R2I")
 call R2I(0.3-0.2-0.1)
 call Preload("PATHNUM done=real_cancel")
 call Preload("PATHNUM case=real_sum native=R2I")
 call R2I(0.1+0.2+0.3)
 call Preload("PATHNUM done=real_sum")
 call Preload("PATHNUM case=real_ratio native=R2I")
 call R2I(7.0/3.0/2.0)
 call Preload("PATHNUM done=real_ratio")
 call Preload("PATHNUM case=real_product native=R2I")
 call R2I(0.1*0.2*0.3)
 call Preload("PATHNUM done=real_product")
 call Preload("PATHNUM case=real_promote native=R2I")
 call R2I(16777217-1.0-2.0)
 call Preload("PATHNUM done=real_promote")
 call Preload("PATHNUM case=int_wrap_add native=I2R")
 call I2R(2147483647+1+1)
 call Preload("PATHNUM done=int_wrap_add")
 call Preload("PATHNUM case=int_wrap_sub native=I2R")
 call I2R(-2147483648-1-1)
 call Preload("PATHNUM done=int_wrap_sub")
 call Preload("PATHNUM case=int_wrap_mul native=I2R")
 call I2R(2147483647*3*3)
 call Preload("PATHNUM done=int_wrap_mul")
 set udg_PathProbeUnit=CreateUnit(Player(0),'hV80',272.0,304.0,90.0)
 call SetUnitMoveSpeed(udg_PathProbeUnit,100.0)
 call FogEnable(false)
 call FogMaskEnable(false)
 call SetCameraPosition(1008.0,1040.0)
 call PathProbeRecord("start_chained_expression")
 set udg_PathProbeTimer=CreateTimer()
 call TimerStart(udg_PathProbeTimer,0.4/2.0/2.0,true,function PathProbeTick)
endfunction
