"""Bind contention, cancellation and successors to unchanged retail evidence."""
import gzip
import hashlib
import json
import sys
from .e2e205_contract import ROOT, fingerprint, validate_bindings

sys.path.insert(0,str(ROOT/'tools/frida'))
from verify_wc3_scheduler_trace import verify as scheduler_verify

CATEGORIES={
    'contention': ('wc3_e2e210.player_contention_retains_ordered_admission_and_saved_queues', []),
    'cancellation': ('wc3_e2e210.cancellation_and_completion_release_preserve_successor_ownership',
                     ['oracle-cancel208','oracle-interrupt209']),
    'successors': ('wc3_e2e210.queued_orders_follow_arrival_combat_and_blocked_completion',
                   ['live-patrol-leg-ownership']),
}
SOURCES=[
    'tools/ghidra/fixtures/retail-e2e-baseline203-1.27.json',
    'tools/ghidra/fixtures/retail-scheduler-contention-1.27.json',
    'tools/ghidra/fixtures/retail-scheduler-contention-1.27.jsonl.gz',
    'tools/frida/verify_wc3_scheduler_trace.py',
    'games/warcraft-3/game/tests/retail_scheduler_contention.h',
    'tools/ghidra/fixtures/retail-cancel208-1.27.json',
    'tools/ghidra/fixtures/retail-cancel208-turning-1.27.jsonl.gz',
    'tools/ghidra/fixtures/retail-cancel208-queue-1.27.jsonl.gz',
    'games/warcraft-3/game/tests/retail_cancel208.h',
    'games/warcraft-3/game/tests/retail_cancel208_scene.h',
    'tools/ghidra/fixtures/retail-interrupt209-1.27.json',
    'tools/ghidra/fixtures/retail-interrupt209-1.27.jsonl.gz',
    'games/warcraft-3/game/tests/retail_interrupt209_scene.h',
    'tools/ghidra/fixtures/research/patrol176-queue.json',
]


def validate(spec,manifest,root=ROOT):
    entries=validate_bindings(spec,manifest,CATEGORIES,SOURCES,'E2E-01.3',root)
    cert=json.loads((root/SOURCES[1]).read_text())
    expected={'runtime/scheduler-contention-102-c.jsonl':cert['capture_sha256'],
              'runtime/scheduler-contention-102-e.jsonl':cert['repeat_sha256']}
    if spec['scheduler_archives']!=expected:raise ValueError('original contention repeat inventory differs')
    return entries


def scheduler(spec,archive,root=ROOT):
    cert=json.loads((root/SOURCES[1]).read_text());observations=[]
    for path,pin in spec['scheduler_archives'].items():
        raw=(archive/path).read_bytes()
        if hashlib.sha256(raw).hexdigest()!=pin:raise ValueError('contention capture pin differs')
        result=scheduler_verify([json.loads(l)for l in raw.splitlines()])
        for key in ('events','paths','denials','resets','waits','retired','pending','pending_boundary','digest','first_window'):
            if result[key]!=cert[key]:raise ValueError('original contention changed: '+key)
        observations.append(result)
    if len(observations)!=2 or observations[0]['stream']!=observations[1]['stream']:
        raise ValueError('complete contention repeats differ')
    portable=gzip.decompress((root/SOURCES[2]).read_bytes())
    if hashlib.sha256(portable).hexdigest()!=cert['filtered_sha256']:
        raise ValueError('portable contention pin differs')
    rows=observations[0]['first_window']
    header='/* Generated by verify_wc3_scheduler_trace.py from pinned retail Scheduler102. */\n'
    header+='/* '+cert['capture_sha256']+' */\nstatic uint32_t const retail_scheduler_contention[][18]={\n'
    header+=''.join('    {'+','.join('UINT32_MAX'if isinstance(v,str)else str(v)for v in row)+'},\n'for row in rows)+'};\n'
    if (root/SOURCES[4]).read_text()!=header:raise ValueError('engine contention words differ')
    return {'observations':2,'events':cert['events'],'paths':cert['paths'],
            'pending_at_completion':cert['pending'],'engine_rows':len(rows),'digest':cert['digest']}
