#!/usr/bin/env python3
"""Copy complete original fine-consumer outputs into the engine regression table."""
import argparse,itertools,json
from pathlib import Path


def header(fixture):
    cases=fixture['cases'];kinds={'endpoint':0,'waypoint':1,'blockers':2}
    if len(cases)!=96:raise ValueError('incomplete consumer matrix')
    rows=[];seen=set()
    for row in cases:
        key=(row['kind'],row['cls'],row['blocked'],row['outer'],row['self_absent'])
        if key in seen or row['kind'] not in kinds or not row['held']:raise ValueError('invalid consumer row')
        seen.add(key)
        held=row['held'][0]['counter']
        if any(s['counter']!=held or s['endpoint_mode']!=(row['kind']=='endpoint') for s in row['held']):
            raise ValueError('consumer scope changed while held')
        values=[kinds[row['kind']],row['cls'],int(row['blocked']),row['blocked_cell'][0],row['outer'],
            int(row['self_absent']),row['count'] if row['kind']=='blockers' else row['result'],held,row['after_counter']]
        rows.append('    {'+','.join(map(str,values))+'}')
    if seen!=set(itertools.product(kinds,range(4),(False,True),range(2),(False,True))):
        raise ValueError('invalid consumer matrix domain')
    return ('/* Original16ee80/167bf0/166140; supplied geometry and outer depths.\n'
            ' * Generated by export_exclusion_consumers.py; no expected-policy model. */\n'
            'typedef struct { unsigned kind,cls,blocked,block_x,outer,absent,result,held,after; } retailExclusionConsumer_t;\n'
            'static retailExclusionConsumer_t const retail_exclusion_consumers[96]={\n'+',\n'.join(rows)+'\n};\n')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--fixture',type=Path,required=True);parser.add_argument('--header',type=Path,required=True)
    args=parser.parse_args();args.header.write_text(header(json.loads(args.fixture.read_text())))


if __name__=='__main__':main()
