#!/usr/bin/env python3
"""Export frozen ordinary ROUTE-01.2 advances for the actual Move consumer.

Invalid-start/retry scenarios are excluded here; their initialized kernels have
separate regressions. Supplied impossible indices remain labelled controls in
the source fixture. No outputs are calculated by a replacement route model.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'tools/ghidra/fixtures/retail-route-consumers-initialized-1.27.json'
OUTPUT = ROOT / 'games/warcraft-3/game/tests/retail_route_consumers.h'
SCENARIOS = ['empty_admitted', 'empty_coarse_denied', 'empty_fine_denied',
             'empty_fine_interval', 'fine_index_state', 'coarse_index_state']


def render():
    fixture = json.loads(SOURCE.read_text())
    assert fixture['consumer_initialization'] == {'entry': '6f0040d0', 'address': '6fd54194', 'word': 0x41200000}
    states, rows = [], []
    def state(visit):
        if visit is None:
            return -1
        s = visit['state']
        assert len(s['fine_words']) <= 48 and len(s['coarse_words']) <= 16
        scalars = [visit['result'], s['fine_count'], s['fine_capacity'], s['fine_index'],
                   s['coarse_count'], s['coarse_capacity'], s['coarse_index'],
                   s['fine_time'], s['coarse_time'], s['delay'], s['retry'],
                   s['fine_bucket'][0], s['fine_bucket'][2],
                   s['coarse_bucket'][0], s['coarse_bucket'][2]]
        values = [','.join(f'0x{v:08x}u' for v in scalars)]
        for key in ['output', 'fine_words', 'coarse_words']:
            words = s[key]
            values.append('{' + (','.join(f'0x{v:08x}u' for v in words) or '0') + '}')
        text = '{' + ','.join(values) + '}'
        if text not in states:
            states.append(text)
        return states.index(text)
    for row in fixture['rows']:
        scenario = row['scenario']
        if scenario not in SCENARIOS:
            continue
        enabled = row.get('adaptive_enabled', scenario == 'coarse_index_state')
        rows.append('{%s}' % ','.join(str(v) for v in [SCENARIOS.index(scenario),
            int(row['map'] == 'wall_gap'), row['cls'], int(enabled), int(row.get('admitted', True)),
            row.get('index', 0), state(row.get('first', row.get('after'))), state(row.get('second'))]))
    assert len(rows) == 208
    return '''/* Generated by tools/ghidra/research/export_route012_consumers.py.
 * Literal original165ae0 results; engine compares its READY/STOP semantics
 * and all represented buffer, work, queue, timestamp and output words. */
typedef struct {
    uint32_t result, count, capacity, index, coarse_count, coarse_capacity, coarse_index;
    uint32_t fine_time, coarse_time, delay, retry, fine_work, fine_queued, coarse_work, coarse_queued;
    uint32_t output[2], points[48], coarse_points[16];
} retailRouteConsumerState_t;
static retailRouteConsumerState_t const retail_route_consumer_states[] = {
''' + ',\n'.join(states) + '''
};
typedef struct { uint32_t scenario, wall, cls, adaptive, admitted, index; int first, second; } retailRouteConsumer_t;
static retailRouteConsumer_t const retail_route_consumers[] = {
''' + ',\n'.join(rows) + '\n};\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = render()
    if args.check:
        assert OUTPUT.read_text() == expected, 'consumer fixture differs from frozen original'
    else:
        OUTPUT.write_text(expected)


if __name__ == '__main__':
    main()
