#!/usr/bin/env python3
"""Reconstruct the complete archived startup RNG observations and engine oracle."""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import struct

PRIMARY=('mixed-observe-1','fixed-observe-1','triad-observe-1',
         'mixed-unlockedB-observe-1','mixed-unlockedB-observe-2')
PROVENANCE=Path('tools/ghidra/fixtures/research/NUM-04.5-expected.json')
ANALYZER=Path('tools/frida/research/NUM-04.5_analyze.py')


def scenes(expected):
    result=[]
    for name in PRIMARY:
        key='NUM-04.5/'+name;c=expected['captures'][key];m=c['milestones']
        races=[int(re.search(r'race=(\d+)',x)[1]) for x in expected['preload_probe_lines'][key] if 'label=race ' in x]
        if not races:
            races=[1]*4+[(x['value']>>30)+1 for x in c['startup_draws'] if x['caller']=='0x6f1e9e25']
        q=[x['value'] for x in c['startup_draws'] if x['caller'] in ('0x6f201e5e','0x6f201ed6')]
        query=[q[0]>>1,-1000+((q[1]*2001)>>32),struct.unpack('<I',struct.pack('<f',(q[2]&0x7fffff)/8388608))[0]] if q else [0,0,0]
        assert len(races)==12
        result.append(dict(name=name,locked=c['locked'],setup_seed=c['lobby_seed'],
            owner=m['first-owner-visit']['owner'],races=races,query=query,race_draws=c['race_draws']))
    return result


def render(data):
    h='/* Frozen NUM-04.5 public startup observations; regenerated by verify_startup171_seed.py. */\n#ifndef RETAIL_STARTUP_171_H\n#define RETAIL_STARTUP_171_H\ntypedef struct { bool locked; uint32_t setup_seed, owner[2], races[12]; int32_t int1,int2; uint32_t real; } retailStartup171_t;\nstatic retailStartup171_t const retail_startup171[]={\n'
    for x in data:
        h+=' {%s,%du,{%du,%du},{%s},%d,%d,0x%08xu},\n'%('true' if x['locked'] else 'false',x['setup_seed'],*x['owner'],','.join(str(i)+'u' for i in x['races']),*x['query'])
    return h+'};\n#endif\n'


def verify_rows(rows,complete):
    assert rows and rows[0]['event']=='metadata'
    assert rows[0]['binary_sha256']=='d51e5680243fc90e19c9d6074f7fac433c466d3cf5f46e2364291725574d8236'
    assert rows[0]['mode']=='observe' and rows[0]['owned']
    assert not any(x['event'] in ('error','observer-error','truncated') for x in rows)
    if complete:
        assert rows[-1]['event']=='trace-end' and rows[-1]['installed']
        assert any(x['event']=='marker' and 'label=complete' in x['value'] for x in rows)
        assert any(x['event']=='separation-visit' for x in rows)
    decision=next(x for x in rows if x['event']=='setup-seed-decision')
    assert decision['owner']==[1768977253,2822785048]
    stamps=[x['tick'] for x in rows if x['event']=='setup-record-tick']
    if stamps:assert stamps[-1]==decision['lobbySeed']
    pref=[x for x in rows if x['event']=='pref-bool' and x['index']==0x6a]
    if pref:assert bool(pref[-1]['result'])==bool(decision['flags']&0x8000)
    return decision


def verify(manifest,archive,expected):
    spec=importlib.util.spec_from_file_location('startup_analyzer',ANALYZER)
    analyzer=importlib.util.module_from_spec(spec);spec.loader.exec_module(analyzer)
    # The arithmetic words come from the separately original-code verified,
    # pinned generator fixture. Do not use the analyzer's workstation PE path.
    random=json.loads(Path('tools/ghidra/fixtures/retail-pathfinding-random-1.27.json').read_text())
    analyzer.WORDS=random['table_words']
    assert hashlib.sha256(ANALYZER.read_bytes()).hexdigest()==expected['analyzer_sha256']
    assert analyzer.reseed45(0x77617233)==expected['war3_streams']
    checked={};owner=stream=0
    for key,pin in manifest['captures'].items():
        path=archive/Path(key).parent/'captures'/Path(key).name/'capture.jsonl';raw=path.read_bytes()
        assert hashlib.sha256(raw).hexdigest()==pin['sha256']
        rows=[json.loads(l) for l in raw.decode().splitlines()]
        verify_rows(rows,pin['complete'])
        got=analyzer.analyze(path);c=expected['captures'][key]
        assert got['mismatch_count']==0 and got['checks']==c['checks']
        for k in ('locked','flags','lobby_seed','game_seed','race_draws','capture_sha256','draw_callers'):
            assert got[k]==c[k],(key,k)
        milestones={}
        draws=[]
        for t in got['timeline']:
            w=t['what']
            if w in c['milestones'] and w not in milestones:
                milestones[w]={k:v for k,v in t.items() if k!='seq'}
            if w=='separation-visit':break
            if w=='draw':draws.append({k:t[k] for k in ('cls','caller','before','after','value','visit')})
        # SetRandomSeed is after first separation; compare full milestone pass.
        for t in got['timeline']:
            if t['what'] in c['milestones'] and t['what'] not in milestones:
                milestones[t['what']]={k:v for k,v in t.items() if k!='seq'}
        assert milestones==c['milestones'];assert draws==c['startup_draws']
        owner+=got['checks'].get('owner-draw-ok',0);stream+=got['checks'].get('stream-draw-ok',0)
        checked[key]=dict(complete=pin['complete'],checks=got['checks'])
    pre={}
    for key,pin in manifest['preloads'].items():
        path=archive/Path(key).parent/'captures'/Path(key).name/'preload.txt';raw=path.read_bytes()
        assert hashlib.sha256(raw).hexdigest()==pin['sha256']
        pre[key]=analyzer.preload_lines(path)
        # Frozen probe projection removes position-only lines; every raw
        # observation/control file is still hash checked and compared in full.
        keep=[x for x in pre[key] if re.search(r'label=(race|query|streams|reseed|complete|start_)',x)]
        assert keep==expected['preload_probe_lines'][key]
    for control,repeat in manifest['controls']:
        assert pre[control]==pre[repeat]
    return dict(passed=True,status='live-exact-map-startup',captures=len(checked),
        complete_captures=sum(x['complete'] for x in checked.values()),profiles=5,
        owner_draws=owner,stream_draws=stream,observer_free_comparisons=len(manifest['controls']),
        incomplete_captures=[k for k,v in checked.items() if not v['complete']],checks=checked)


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--expected',type=Path,default=Path('tools/ghidra/fixtures/retail-startup-seed171-1.27.json'))
    ap.add_argument('--archive',type=Path,required=True)
    ap.add_argument('--header',type=Path,default=Path('games/warcraft-3/game/tests/fixtures/retail_startup_seed_171.h'))
    ap.add_argument('--output',type=Path,required=True)
    args=ap.parse_args();m=json.loads(args.expected.read_text());raw=PROVENANCE.read_bytes()
    assert hashlib.sha256(raw).hexdigest()==m['provenance_sha256']
    expected=json.loads(raw);assert scenes(expected)==m['scenes']
    assert args.header.read_text()==render(m['scenes'])
    result=verify(m,args.archive,expected);args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items() if k!='checks'},indent=2))


if __name__=='__main__':main()
