/* Frozen NUM-04.5 public startup observations; regenerated by verify_startup171_seed.py. */
#ifndef RETAIL_STARTUP_171_H
#define RETAIL_STARTUP_171_H
typedef struct { bool locked; uint32_t setup_seed, owner[2], races[12]; int32_t int1,int2; uint32_t real; } retailStartup171_t;
static retailStartup171_t const retail_startup171[]={
 {true,81434830u,{3946970562u,277349488u},{1u,1u,1u,1u,2u,1u,3u,3u,4u,4u,1u,4u},2130728302,929,0x3f03fb84u},
 {true,81476501u,{3292812501u,548955360u},{1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u,1u},371411726,449,0x3f08a9aau},
 {true,77115558u,{4273436052u,209508436u},{1u,1u,1u,1u,1u,3u,4u,4u,4u,4u,4u,4u},0,0,0x00000000u},
 {false,82172056u,{4160792303u,1486880788u},{1u,1u,1u,1u,2u,1u,3u,1u,4u,2u,1u,1u},735845865,-290,0x3ba6ef00u},
 {false,82215974u,{2707349937u,2824099852u},{1u,1u,1u,1u,2u,1u,3u,3u,4u,1u,1u,3u},436079602,-575,0x3f3dc362u},
};
#endif
