#!/usr/bin/env python3
"""Regenerate the WC3 credits contributor list from GitHub.

Queries the repository's contributors (already sorted by commit count,
highest first), drops bots, and writes a C header with one comma-separated
string that the credits screen embeds.

    python3 tools/update_credits.py
    python3 tools/update_credits.py --repo corepunch/open-realm --dry-run

Set GITHUB_TOKEN (or GH_TOKEN) to avoid the anonymous API rate limit.
"""

import argparse
import json
import os
import sys
import urllib.request

DEFAULT_REPO = "corepunch/open-realm"
DEFAULT_OUT = os.path.join(os.path.dirname(__file__), "..", "games",
                           "warcraft-3", "menu", "generated", "contributors.h")

# Automation accounts GitHub reports as type "User".
NON_HUMAN_LOGINS = {"openhands-agent", "orbisai0security"}


def api(path):
    req = urllib.request.Request("https://api.github.com" + path, headers={
        "Accept": "application/vnd.github+json",
        "User-Agent": "openwarcraft3-update-credits",
    })
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if token:
        req.add_header("Authorization", "Bearer " + token)
    with urllib.request.urlopen(req) as resp:
        return json.load(resp)


def contributors(repo):
    page = 1
    while True:
        batch = api(f"/repos/{repo}/contributors?per_page=100&page={page}")
        if not batch:
            return
        yield from batch
        page += 1


def is_human(c):
    login = c["login"]
    return (c.get("type") == "User"
            and not login.endswith("[bot]")
            and login.lower() not in NON_HUMAN_LOGINS)


def display_name(login):
    name = (api(f"/users/{login}").get("name") or "").strip()
    return name or login


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--repo", default=DEFAULT_REPO)
    ap.add_argument("-o", "--output", default=DEFAULT_OUT)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the list instead of writing the header")
    args = ap.parse_args()

    names = []
    for c in contributors(args.repo):
        if is_human(c):
            name = display_name(c["login"])
            if name not in names:
                names.append(name)

    joined = ", ".join(names)
    if args.dry_run:
        print(joined)
        return 0

    with open(args.output, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/update_credits.py from GitHub contributors\n"
                f" * of {args.repo}, sorted by contribution count. Do not edit. */\n"
                "#ifndef CONTRIBUTORS_H\n#define CONTRIBUTORS_H\n\n"
                f"#define WC3_CREDITS_CONTRIBUTORS {c_string(joined)}\n\n"
                "#endif /* CONTRIBUTORS_H */\n")
    print(f"wrote {len(names)} contributors to {os.path.normpath(args.output)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
