/* Original Interrupt209 public gameplay probe, no synthesized expected values. */
static char const interrupt209_scene[] =
    "globals\n"
    "constant unitstate UNIT_STATE_LIFE=ConvertUnitState(0)\n"
    "constant unitevent EVENT_UNIT_SPELL_CHANNEL=ConvertUnitEvent(289)\n"
    "constant unitevent EVENT_UNIT_SPELL_CAST=ConvertUnitEvent(290)\n"
    "constant unitevent EVENT_UNIT_SPELL_EFFECT=ConvertUnitEvent(291)\n"
    "endglobals\n"
    "globals\n"
    " timer udg_I209Timer=null\n"
    " integer udg_I209Tick=0\n"
    " unit udg_I209Caster=null\n"
    " unit udg_I209Target=null\n"
    " unit array udg_I209Peer\n"
    " integer udg_I209Channel=0\n"
    " integer udg_I209Cast=0\n"
    " integer udg_I209Effect=0\n"
    " integer udg_I209Orders=0\n"
    " boolean udg_I209Resumed=false\n"
    "endglobals\n"
    "function I209Mark takes string label returns nothing\n"
    " call Preload(\"I209 tick=\"+I2S(udg_I209Tick)+\" label=\"+label)\n"
    "endfunction\n"
    "function I209Order takes nothing returns nothing\n"
    " set udg_I209Orders=udg_I209Orders+1\n"
    " call I209Mark(\"issued order=\"+I2S(GetIssuedOrderId()))\n"
    " if GetIssuedOrderId()==OrderId(\"undefend\") and not udg_I209Resumed then\n"
    "  set udg_I209Resumed=true\n"
    "  call I209Mark(\"release-before-mutation\")\n"
    "  call IssuePointOrder(udg_I209Caster,\"move\",1536,1536)\n"
    "  call I209Mark(\"release-after-mutation\")\n"
    " endif\n"
    "endfunction\n"
    "function I209Channel takes nothing returns nothing\n"
    " local integer i=0\n"
    " local boolean accepted=false\n"
    " set udg_I209Channel=udg_I209Channel+1\n"
    " call I209Mark(\"channel-before-mutation\")\n"
    " loop\n"
    "  exitwhen i==4\n"
    "  call I209Mark(\"remove-before role=\"+I2S(i))\n"
    "  call RemoveUnit(udg_I209Peer[i])\n"
    "  call I209Mark(\"remove-after role=\"+I2S(i))\n"
    "  if i==0 then\n"
    "   set accepted=IssueImmediateOrder(udg_I209Peer[i],\"stop\")\n"
    "  elseif i==1 then\n"
    "   set accepted=IssueImmediateOrder(udg_I209Peer[i],\"holdposition\")\n"
    "  elseif i==2 then\n"
    "   set accepted=IssueTargetOrder(udg_I209Peer[i],\"move\",udg_I209Target)\n"
    "  else\n"
    "   set accepted=IssuePointOrder(udg_I209Peer[i],\"move\",288,1800)\n"
    "  endif\n"
    "  if accepted then\n"
    "   call I209Mark(\"accepted role=\"+I2S(i)+\" order=\"+I2S(GetUnitCurrentOrder(udg_I209Peer[i])))\n"
    "  else\n"
    "   call I209Mark(\"rejected role=\"+I2S(i)+\" order=\"+I2S(GetUnitCurrentOrder(udg_I209Peer[i])))\n"
    "  endif\n"
    "  set i=i+1\n"
    " endloop\n"
    " call IssuePointOrder(udg_I209Caster,\"move\",288,1536)\n"
    " call I209Mark(\"channel-after-mutation\")\n"
    "endfunction\n"
    "function I209Cast takes nothing returns nothing\n"
    " set udg_I209Cast=udg_I209Cast+1\n"
    " call I209Mark(\"cast\")\n"
    "endfunction\n"
    "function I209Effect takes nothing returns nothing\n"
    " set udg_I209Effect=udg_I209Effect+1\n"
    " call I209Mark(\"effect\")\n"
    "endfunction\n"
    "function I209Tick takes nothing returns nothing\n"
    " local trigger tr=null\n"
    " local integer i=0\n"
    " set udg_I209Tick=udg_I209Tick+1\n"
    " if udg_I209Tick==20 then\n"
    "  call I209Mark(\"begin-setup\")\n"
    "  set udg_I209Caster=CreateUnit(Player(0),'Hpal',288,288,0)\n"
    "  set udg_I209Target=CreateUnit(Player(0),'hfoo',1536,288,0)\n"
    "  call SelectHeroSkill(udg_I209Caster,'AHhb')\n"
    "  call SetUnitState(udg_I209Target,UNIT_STATE_LIFE,200)\n"
    "  loop\n"
    "   exitwhen i==4\n"
    "   set udg_I209Peer[i]=CreateUnit(Player(0),'hfoo',288,900+200*i,0)\n"
    "   set tr=CreateTrigger()\n"
    "   call TriggerRegisterUnitEvent(tr,udg_I209Peer[i],EVENT_UNIT_ISSUED_ORDER)\n"
    "   call TriggerRegisterUnitEvent(tr,udg_I209Peer[i],EVENT_UNIT_ISSUED_POINT_ORDER)\n"
    "   call TriggerRegisterUnitEvent(tr,udg_I209Peer[i],EVENT_UNIT_ISSUED_TARGET_ORDER)\n"
    "   call TriggerAddAction(tr,function I209Order)\n"
    "   call IssuePointOrder(udg_I209Peer[i],\"move\",1800,900+200*i)\n"
    "   set i=i+1\n"
    "  endloop\n"
    "  set tr=CreateTrigger()\n"
    "  call TriggerRegisterUnitEvent(tr,udg_I209Caster,EVENT_UNIT_SPELL_CHANNEL)\n"
    "  call TriggerAddAction(tr,function I209Channel)\n"
    "  set tr=CreateTrigger()\n"
    "  call TriggerRegisterUnitEvent(tr,udg_I209Caster,EVENT_UNIT_SPELL_CAST)\n"
    "  call TriggerAddAction(tr,function I209Cast)\n"
    "  set tr=CreateTrigger()\n"
    "  call TriggerRegisterUnitEvent(tr,udg_I209Caster,EVENT_UNIT_SPELL_EFFECT)\n"
    "  call TriggerAddAction(tr,function I209Effect)\n"
    "  if IssueTargetOrder(udg_I209Caster,\"holybolt\",udg_I209Target) then\n"
    "   call I209Mark(\"spell-accepted\")\n"
    "  else\n"
    "   call I209Mark(\"spell-rejected\")\n"
    "  endif\n"
    " endif\n"
    " if udg_I209Tick>=20 then\n"
    "  call I209Mark(\"sample order=\"+I2S(GetUnitCurrentOrder(udg_I209Caster))+\" x=\"+R2SW(GetUnitX(udg_I209Caster),1,4)+\" y=\"+R2SW(GetUnitY(udg_I209Caster),1,4)+\" life=\"+R2SW(GetUnitState(udg_I209Target,UNIT_STATE_LIFE),1,4)+\" channel=\"+I2S(udg_I209Channel)+\" cast=\"+I2S(udg_I209Cast)+\" effect=\"+I2S(udg_I209Effect)+\" orders=\"+I2S(udg_I209Orders))\n"
    " endif\n"
    " if udg_I209Tick==140 then\n"
    "  call I209Mark(\"complete\")\n"
    "  call PauseTimer(udg_I209Timer)\n"
    "  call PreloadGenEnd(\"@OUTPUT@\")\n"
    " endif\n"
    "endfunction\n"
    "function PathProbeInit takes nothing returns nothing\n"
    " call FogEnable(false)\n"
    " call FogMaskEnable(false)\n"
    " call SetTimeOfDayScale(0)\n"
    " call SetFloatGameState(GAME_STATE_TIME_OF_DAY,12)\n"
    " call PreloadGenClear()\n"
    " call PreloadGenStart()\n"
    " set udg_I209Timer=CreateTimer()\n"
    " call TimerStart(udg_I209Timer,0.1,true,function I209Tick)\n"
    "endfunction\n"
    "function main takes nothing returns nothing\n"
    "call PathProbeInit()\n"
    "endfunction\n"
    "function I209Check takes nothing returns nothing\n"
    "call BJassAssert(udg_I209Channel==1 and udg_I209Cast==0 and udg_I209Effect==0,\"interrupted arrival never casts twice\")\n"
    "call BJassAssert(GetUnitCurrentOrder(udg_I209Caster)==0 and udg_I209Resumed,\"replacement Move completed\")\n"
    "call BJassAssert(udg_I209Orders==12,\"each peer retired once, no suspended issued event\")\n"
    "endfunction\n"
;
