/* Gameplay and observation boundaries from cancel208_probe.j; test main calls PathProbeInit. */
static char const cancel208_scene[] =
    "globals\n"
    " timer udg_C208Timer=null\n"
    " integer udg_C208Tick=0\n"
    " unit array udg_C208U\n"
    "endglobals\n"
    "function C208Mark takes string label returns nothing\n"
    " local integer i=0\n"
    " local string s=\"C208 tick=\"+I2S(udg_C208Tick)+\" label=\"+label\n"
    " loop\n"
    "  exitwhen i==8\n"
    "  set s=s+\" u\"+I2S(i)+\"=\"+R2S(GetUnitX(udg_C208U[i]))+\",\"+R2S(GetUnitY(udg_C208U[i]))+\",\"+R2S(GetUnitFacing(udg_C208U[i]))+\",\"+I2S(GetUnitCurrentOrder(udg_C208U[i]))\n"
    "  set i=i+1\n"
    " endloop\n"
    " call Preload(s)\n"
    "endfunction\n"
    "function C208Tick takes nothing returns nothing\n"
    " set udg_C208Tick=udg_C208Tick+1\n"
    " if udg_C208Tick==4 then\n"
    "  call IssuePointOrder(udg_C208U[2],\"move\",1536,640)\n"
    "  call IssuePointOrder(udg_C208U[3],\"move\",1536,832)\n"
    "  call IssuePointOrder(udg_C208U[4],\"move\",1536,1024)\n"
    " endif\n"
    " if udg_C208Tick==5 then\n"
    "  call SetUnitFacingTimed(udg_C208U[0],270,1.2)\n"
    "  call SetUnitFacingTimed(udg_C208U[1],270,1.2)\n"
    "  call SetUnitFacingTimed(udg_C208U[2],270,1.2)\n"
    "  call SetUnitFacingTimed(udg_C208U[5],270,1.2)\n"
    "  call SetUnitFacingTimed(udg_C208U[6],90,1.2)\n"
    "  call C208Mark(\"before_stop_natural_turn\")\n"
    "  call IssueImmediateOrder(udg_C208U[3],\"stop\")\n"
    "  call IssuePointOrder(udg_C208U[4],\"move\",128,1024)\n"
    "  call C208Mark(\"after_stop_natural_turn\")\n"
    " endif\n"
    " if udg_C208Tick==6 then\n"
    "  call C208Mark(\"before_cancel_angular\")\n"
    "  call IssueImmediateOrder(udg_C208U[0],\"stop\")\n"
    "  call IssueImmediateOrder(udg_C208U[1],\"holdposition\")\n"
    "  call IssueImmediateOrder(udg_C208U[2],\"stop\")\n"
    "  call IssuePointOrder(udg_C208U[5],\"move\",1536,1216)\n"
    "  call IssueImmediateOrder(udg_C208U[7],\"stop\")\n"
    "  call C208Mark(\"after_cancel_angular\")\n"
    " endif\n"
    " call C208Mark(\"sample\")\n"
    " if udg_C208Tick==80 then\n"
    "  call C208Mark(\"complete\")\n"
    "  call PauseTimer(udg_C208Timer)\n"
    "  call PreloadGenEnd(\"@OUTPUT@\")\n"
    " endif\n"
    "endfunction\n"
    "function PathProbeInit takes nothing returns nothing\n"
    " local integer i=0\n"
    " call FogEnable(false)\n"
    " call FogMaskEnable(false)\n"
    " call SetTimeOfDayScale(0)\n"
    " call SetFloatGameState(GAME_STATE_TIME_OF_DAY,12)\n"
    " call PreloadGenClear()\n"
    " call PreloadGenStart()\n"
    " call C208Mark(\"start\")\n"
    " loop\n"
    "  exitwhen i==8\n"
    "  set udg_C208U[i]=CreateUnit(Player(0),'hF00',512,256+192*i,0)\n"
    "  call SetUnitAcquireRange(udg_C208U[i],0)\n"
    "  set i=i+1\n"
    " endloop\n"
    " call SetUnitFacing(udg_C208U[2],180)\n"
    " call SetUnitFacing(udg_C208U[3],180)\n"
    " call SetUnitFacing(udg_C208U[4],180)\n"
    " call C208Mark(\"created\")\n"
    " set udg_C208Timer=CreateTimer()\n"
    " call TimerStart(udg_C208Timer,0.1,true,function C208Tick)\n"
    "endfunction\n"
    "function main takes nothing returns nothing\n"
    "call PathProbeInit()\n"
    "endfunction\n"
;
