#ifndef g_metadata_h
#define g_metadata_h

#include <stddef.h>
#include "g_local.h"

#define M(id,row,type,member,kind) \
    { id, offsetof(edict_t, row), offsetof(type, member), kind }
#define MI(id,member,kind) M(id,itemData,ItemData_t,member,kind)
#define MP(id,member,kind) M(id,profile,UnitProfile_t,member,kind)
#define MA(id,member,kind) M(id,abilities,UnitAbilities_t,member,kind)
#define MB(id,member,kind) M(id,balance,UnitBalance_t,member,kind)
#define MD(id,member,kind) M(id,data,UnitData_t,member,kind)
#define MU(id,member,kind) M(id,ui,UnitUI_t,member,kind)
#define MW(id,member,kind) M(id,weapons,UnitWeapons_t,member,kind)

unitMeta_t const UnitsMetaData[] = {
    MI("iabi",abilList,BZ_FIELD_CSTR), MI("iarm",armor,BZ_FIELD_U32),
    MI("icla",itemClass,BZ_FIELD_CSTR), MI("iclb",colorB,BZ_FIELD_U32),
    MI("iclg",colorG,BZ_FIELD_U32), MI("iclr",colorR,BZ_FIELD_U32),
    MI("icid",cooldownID,BZ_FIELD_CSTR), MI("idrp",drop,BZ_FIELD_BOOL),
    MI("idro",droppable,BZ_FIELD_BOOL), MI("ifil",file,BZ_FIELD_CSTR),
    MI("igol",goldcost,BZ_FIELD_U32), MI("ihtp",HP,BZ_FIELD_U32),
    MI("iicd",ignoreCD,BZ_FIELD_BOOL), MI("ilev",level,BZ_FIELD_U32),
    MI("ilum",lumbercost,BZ_FIELD_U32), MI("imor",morph,BZ_FIELD_BOOL),
    MI("ilvo",oldLevel,BZ_FIELD_U32), MI("iper",perishable,BZ_FIELD_BOOL),
    MI("iprn",pickRandom,BZ_FIELD_BOOL), MI("ipow",powerup,BZ_FIELD_BOOL),
    MI("ipri",prio,BZ_FIELD_U32), MI("isca",scale,BZ_FIELD_FLOAT),
    MI("issc",selectionSize,BZ_FIELD_FLOAT), MI("isel",sellable,BZ_FIELD_BOOL),
    MI("ipaw",pawnable,BZ_FIELD_BOOL), MI("isto",stockMax,BZ_FIELD_U32),
    MI("istr",stockRegen,BZ_FIELD_U32), MI("isst",stockStart,BZ_FIELD_U32),
    MI("iusa",usable,BZ_FIELD_BOOL), MI("iuse",uses,BZ_FIELD_U32),
    MP("uani",animProps,BZ_FIELD_CSTR), MP("uico",art,BZ_FIELD_CSTR),
    MP("iico",itemArt,BZ_FIELD_CSTR), MP("uaap",attachmentAnimProps,BZ_FIELD_CSTR),
    MP("ualp",attachmentLinkProps,BZ_FIELD_CSTR), MP("uawt",awakenTip,BZ_FIELD_CSTR),
    MP("ubpr",boneProps,BZ_FIELD_CSTR), MP("ubsl",buildingSoundLabel,BZ_FIELD_CSTR),
    MP("ubui",builds,BZ_FIELD_CSTR), MP("ubpx",buttonPosX,BZ_FIELD_CSTR),
    MP("ubpy",buttonPosY,BZ_FIELD_CSTR), MP("ucua",casterUpgradeArt,BZ_FIELD_CSTR),
    MP("ucun",casterUpgradeName,BZ_FIELD_CSTR), MP("ucut",casterUpgradeTip,BZ_FIELD_CSTR),
    MP("udep",dependencyOr,BZ_FIELD_CSTR), MP("ides",description,BZ_FIELD_CSTR),
    MP("unsf",editorSuffix,BZ_FIELD_CSTR), MP("uhot",hotkey,BZ_FIELD_CSTR),
    MP("ulfi",loopingSoundFadeIn,BZ_FIELD_CSTR), MP("ulfo",loopingSoundFadeOut,BZ_FIELD_CSTR),
    MP("umki",makeItems,BZ_FIELD_CSTR), MP("uma1",attack[0].arc,BZ_FIELD_FLOAT),
    MP("uma2",attack[1].arc,BZ_FIELD_FLOAT), MP("ua1m",attack[0].art,BZ_FIELD_CSTR),
    MP("ua2m",attack[1].art,BZ_FIELD_CSTR), MP("umh1",attack[0].homing,BZ_FIELD_BOOL),
    MP("umh2",attack[1].homing,BZ_FIELD_BOOL), MP("ua1z",attack[0].speed,BZ_FIELD_FLOAT),
    MP("ua2z",attack[1].speed,BZ_FIELD_FLOAT), MP("umsl",movementSoundLabel,BZ_FIELD_CSTR),
    MP("unam",name,BZ_FIELD_CSTR), MP("upro",properNames,BZ_FIELD_CSTR),
    MP("ursl",randomSoundLabel,BZ_FIELD_CSTR), MP("urqc",requiresCount,BZ_FIELD_CSTR),
    MP("ureq",requires,BZ_FIELD_CSTR), MP("urq1",requiresLevel[0],BZ_FIELD_CSTR),
    MP("urq2",requiresLevel[1],BZ_FIELD_CSTR), MP("urq3",requiresLevel[2],BZ_FIELD_CSTR),
    MP("urq4",requiresLevel[3],BZ_FIELD_CSTR), MP("urq5",requiresLevel[4],BZ_FIELD_CSTR),
    MP("urq6",requiresLevel[5],BZ_FIELD_CSTR), MP("urq7",requiresLevel[6],BZ_FIELD_CSTR),
    MP("urq8",requiresLevel[7],BZ_FIELD_CSTR), MP("urqa",requiresAmount,BZ_FIELD_CSTR),
    MP("ures",researches,BZ_FIELD_CSTR), MP("urev",revive,BZ_FIELD_CSTR),
    MP("utpr",reviveTip,BZ_FIELD_CSTR), MP("ussi",scoreScreenIcon,BZ_FIELD_CSTR),
    MP("usei",sellItems,BZ_FIELD_CSTR), MP("useu",sellUnits,BZ_FIELD_CSTR),
    MP("uspa",specialArt,BZ_FIELD_CSTR), MP("utaa",targetArt,BZ_FIELD_CSTR),
    MP("utip",tip,BZ_FIELD_CSTR), MP("utra",trains,BZ_FIELD_CSTR),
    MP("urva",reviveAt,BZ_FIELD_CSTR), MP("utub",uberTip,BZ_FIELD_CSTR),
    MP("uupt",upgrade,BZ_FIELD_CSTR),
    MA("uabi",abilList,BZ_FIELD_CSTR), MA("udaa",auto_,BZ_FIELD_BOOL),
    MA("uhab",heroAbilList,BZ_FIELD_CSTR),
    MB("uagi",agility,BZ_FIELD_U32), MB("uagp",agilityPerLevel,BZ_FIELD_FLOAT),
    MB("ubld",buildTime,BZ_FIELD_U32), MB("ubdi",goldBountyDice,BZ_FIELD_U32),
    MB("ubba",goldBountyBase,BZ_FIELD_U32), MB("ubsi",goldBountySides,BZ_FIELD_U32),
    MB("ulbd",lumberBountyDice,BZ_FIELD_U32), MB("ulba",lumberBountyBase,BZ_FIELD_U32),
    MB("ulbs",lumberBountySides,BZ_FIELD_U32), MB("ucol",collision,BZ_FIELD_FLOAT),
    MD("ucod",collision,BZ_FIELD_FLOAT), MB("udef",baseArmor,BZ_FIELD_U32),
    MB("udfc",armor,BZ_FIELD_FLOAT), MB("udty",defenseType,BZ_FIELD_CSTR),
    MB("udup",armorPerUpgrade,BZ_FIELD_U32), MB("ufma",foodMade,BZ_FIELD_U32),
    MB("ufoo",foodUsed,BZ_FIELD_U32), MB("ugol",goldCost,BZ_FIELD_U32),
    MB("ugor",goldRep,BZ_FIELD_U32), MB("uhpm",maxHealth,BZ_FIELD_FLOAT),
    MB("uint",intelligence,BZ_FIELD_U32), MB("uinp",intelligencePerLevel,BZ_FIELD_FLOAT),
    MU("ubdg",isBuilding,BZ_FIELD_BOOL), MB("ulev",level,BZ_FIELD_U32),
    MB("ulum",lumberCost,BZ_FIELD_U32), MB("ulur",lumberRep,BZ_FIELD_U32),
    MB("umpi",initialMana,BZ_FIELD_FLOAT), MB("umpm",maxMana,BZ_FIELD_FLOAT),
    MB("umas",maxSpeed,BZ_FIELD_FLOAT), MB("umis",minSpeed,BZ_FIELD_FLOAT),
    MB("unbr",nbrandom,BZ_FIELD_U32), MB("usin",nightSightRadius,BZ_FIELD_FLOAT),
    MB("upap",preventPlace,BZ_FIELD_CSTR), MB("upra",primaryAttribute,BZ_FIELD_CSTR),
    MB("uhpr",healthRegen,BZ_FIELD_FLOAT), MB("umpr",manaRegen,BZ_FIELD_FLOAT),
    MB("uhrt",healthRegenType,BZ_FIELD_CSTR), MB("urtm",reptm,BZ_FIELD_U32),
    MB("urpo",repulse,BZ_FIELD_U32), MB("urpg",repulseGroup,BZ_FIELD_U32),
    MB("urpp",repulseParam,BZ_FIELD_FLOAT), MB("urpr",repulsePrio,BZ_FIELD_U32),
    MB("upar",requirePlace,BZ_FIELD_CSTR), MB("usid",sightRadius,BZ_FIELD_FLOAT),
    MB("umvs",speed,BZ_FIELD_FLOAT), MB("usma",stockMax,BZ_FIELD_U32),
    MB("usrg",stockRegen,BZ_FIELD_U32), MB("usst",stockStart,BZ_FIELD_U32),
    MB("ustr",strength,BZ_FIELD_U32), MB("ustp",strengthPerLevel,BZ_FIELD_FLOAT),
    MB("util",tilesets,BZ_FIELD_CSTR), MB("utyp",type,BZ_FIELD_CSTR),
    MB("upgr",upgrades,BZ_FIELD_CSTR),
    MD("uabr",buffRadius,BZ_FIELD_FLOAT), MD("uabt",buffType,BZ_FIELD_CSTR),
    MD("ucbo",canBuildOn,BZ_FIELD_BOOL), MD("ufle",canFlee,BZ_FIELD_BOOL),
    MD("usle",canSleep,BZ_FIELD_BOOL), MD("ucar",cargoSize,BZ_FIELD_U32),
    MD("udtm",death,BZ_FIELD_FLOAT), MD("udea",deathType,BZ_FIELD_U32),
    MD("ulos",useExtendedLineOfSight,BZ_FIELD_BOOL), MD("ufor",formationRank,BZ_FIELD_U32),
    MD("uibo",isBuildOn,BZ_FIELD_BOOL), MD("umvf",moveFloor,BZ_FIELD_FLOAT),
    MD("umvh",moveHeight,BZ_FIELD_FLOAT), MD("umvt",moveTypeName,BZ_FIELD_CSTR),
    MD("upru",nameCount,BZ_FIELD_U32), MD("uori",orientationInterpolation,BZ_FIELD_U32),
    MD("upat",pathingTexture,BZ_FIELD_CSTR), MD("upoi",points,BZ_FIELD_U32),
    MD("upri",priority,BZ_FIELD_U32), MD("uprw",propWin,BZ_FIELD_FLOAT),
    MD("urac",race,BZ_FIELD_CSTR), MD("upaw",requireWaterRadius,BZ_FIELD_FLOAT),
    MD("utar",targetType,BZ_FIELD_CSTR), MD("umvr",turnRate,BZ_FIELD_FLOAT),
    MU("uarm",armorType,BZ_FIELD_U32), MU("uble",blend,BZ_FIELD_FLOAT),
    MU("uclb",tintBlue,BZ_FIELD_U32), MU("ushb",buildingShadowTexture,BZ_FIELD_CSTR),
    MU("ucam",campaign,BZ_FIELD_BOOL), MU("utcc",customTeamColor,BZ_FIELD_BOOL),
    MU("udro",dropItems,BZ_FIELD_BOOL), MU("uept",elevationSamplePoints,BZ_FIELD_U32),
    MU("uerd",elevationSampleRadius,BZ_FIELD_FLOAT), MU("umdl",modelFile,BZ_FIELD_CSTR),
    MU("uver",fileVerFlags,BZ_FIELD_U32), MU("ufrd",fogOfWarSampleRadius,BZ_FIELD_FLOAT),
    MU("uclg",tintGreen,BZ_FIELD_U32), MU("uhos",hostilePal,BZ_FIELD_BOOL),
    MU("uine",inEditor,BZ_FIELD_BOOL), MU("umxp",maxPitchDegrees,BZ_FIELD_FLOAT),
    MU("umxr",maxRollDegrees,BZ_FIELD_FLOAT), MU("usca",modelScale,BZ_FIELD_FLOAT),
    MU("unbm",neutralBuildingMinimapIcon,BZ_FIELD_BOOL), MU("uhhb",hideHeroBar,BZ_FIELD_BOOL),
    MU("uhhm",hideHeroMinimap,BZ_FIELD_BOOL), MU("uhhd",hideHeroDeathMsg,BZ_FIELD_BOOL),
    MU("uhom",hideOnMinimap,BZ_FIELD_BOOL), MU("uocc",occluderHeight,BZ_FIELD_FLOAT),
    MU("uclr",tintRed,BZ_FIELD_U32), MU("urun",animationRunSpeed,BZ_FIELD_FLOAT),
    MU("ussc",selectionScale,BZ_FIELD_FLOAT), MU("uscb",scaleProjectiles,BZ_FIELD_BOOL),
    MU("usew",selectionCircleOnWater,BZ_FIELD_BOOL), MU("uslz",selectionCircleHeight,BZ_FIELD_FLOAT),
    MU("ushh",shadowHeight,BZ_FIELD_FLOAT), MU("ushr",waterShadow,BZ_FIELD_BOOL),
    MU("ushw",shadowWidth,BZ_FIELD_FLOAT), MU("ushx",shadowCenterX,BZ_FIELD_FLOAT),
    MU("ushy",shadowCenterY,BZ_FIELD_FLOAT), MU("uspe",special,BZ_FIELD_CSTR),
    MU("utco",teamColor,BZ_FIELD_U32), MU("utss",tilesetSpecific,BZ_FIELD_BOOL),
    MU("uubs",groundTexture,BZ_FIELD_CSTR), MU("ushu",unitShadowTexture,BZ_FIELD_CSTR),
    MU("usnd",soundLabel,BZ_FIELD_CSTR), MU("uuch",useClickHelper,BZ_FIELD_BOOL),
    MU("uwal",animationWalkSpeed,BZ_FIELD_FLOAT),
    MW("uacq",acquisitionRange,BZ_FIELD_FLOAT),
    MW("ua1t",attack1.attackType,BZ_FIELD_CSTR), MW("ua2t",attack2.attackType,BZ_FIELD_CSTR),
    MW("ubs1",attack1.backswingPoint,BZ_FIELD_FLOAT), MW("ubs2",attack2.backswingPoint,BZ_FIELD_FLOAT),
    MW("ucbs",castBackSwing,BZ_FIELD_FLOAT), MW("ucpt",castPoint,BZ_FIELD_FLOAT),
    MW("ua1c",attack1.cooldown,BZ_FIELD_FLOAT), MW("ua2c",attack2.cooldown,BZ_FIELD_FLOAT),
    MW("udl1",attack1.damageLossFactor,BZ_FIELD_FLOAT), MW("udl2",attack2.damageLossFactor,BZ_FIELD_FLOAT),
    MW("ua1d",attack1.damageDice,BZ_FIELD_U32), MW("ua2d",attack2.damageDice,BZ_FIELD_U32),
    MW("ua1b",attack1.damageBase,BZ_FIELD_U32), MW("ua2b",attack2.damageBase,BZ_FIELD_U32),
    MW("udp1",attack1.damagePoint,BZ_FIELD_FLOAT), MW("udp2",attack2.damagePoint,BZ_FIELD_FLOAT),
    MW("udu1",attack1.damageUpgradeAmount,BZ_FIELD_U32), MW("udu2",attack2.damageUpgradeAmount,BZ_FIELD_U32),
    MW("ua1f",attack1.areaFull,BZ_FIELD_FLOAT), MW("ua2f",attack2.areaFull,BZ_FIELD_FLOAT),
    MW("ua1h",attack1.areaMedium,BZ_FIELD_FLOAT), MW("ua2h",attack2.areaMedium,BZ_FIELD_FLOAT),
    MW("uhd1",attack1.factorMedium,BZ_FIELD_FLOAT), MW("uhd2",attack2.factorMedium,BZ_FIELD_FLOAT),
    MW("uisz",impactSwimZ,BZ_FIELD_FLOAT), MW("uimz",impactHeight,BZ_FIELD_FLOAT),
    MW("ulsz",launchSwimZ,BZ_FIELD_FLOAT), MD("ulpx",launchOffsetX,BZ_FIELD_FLOAT),
    MD("ulpy",launchOffsetY,BZ_FIELD_FLOAT), MD("ulpz",launchOffsetZ,BZ_FIELD_FLOAT),
    MW("uamn",minimumAttackRange,BZ_FIELD_FLOAT), MW("ua1q",attack1.areaSmall,BZ_FIELD_FLOAT),
    MW("ua2q",attack2.areaSmall,BZ_FIELD_FLOAT), MW("uqd1",attack1.factorSmall,BZ_FIELD_FLOAT),
    MW("uqd2",attack2.factorSmall,BZ_FIELD_FLOAT), MW("ua1r",attack1.range,BZ_FIELD_FLOAT),
    MW("ua2r",attack2.range,BZ_FIELD_FLOAT), MW("urb1",attack1.rangeBuffer,BZ_FIELD_FLOAT),
    MW("urb2",attack2.rangeBuffer,BZ_FIELD_FLOAT), MW("uwu1",attack1.showUI,BZ_FIELD_BOOL),
    MW("uwu2",attack2.showUI,BZ_FIELD_BOOL), MW("ua1s",attack1.damageSides,BZ_FIELD_U32),
    MW("ua2s",attack2.damageSides,BZ_FIELD_U32), MW("usd1",attack1.spillDistance,BZ_FIELD_FLOAT),
    MW("usd2",attack2.spillDistance,BZ_FIELD_FLOAT), MW("usr1",attack1.spillRadius,BZ_FIELD_FLOAT),
    MW("usr2",attack2.spillRadius,BZ_FIELD_FLOAT), MW("ua1p",attack1.areaTargets,BZ_FIELD_U32),
    MW("ua2p",attack2.areaTargets,BZ_FIELD_U32), MW("utc1",attack1.maxTargets,BZ_FIELD_U32),
    MW("utc2",attack2.maxTargets,BZ_FIELD_U32), MW("ua1g",attack1.targetsAllowed,BZ_FIELD_U32),
    MW("ua2g",attack2.targetsAllowed,BZ_FIELD_U32), MW("uaen",attacksEnabled,BZ_FIELD_U32),
    MW("ua1w",attack1.weaponType,BZ_FIELD_CSTR), MW("ua2w",attack2.weaponType,BZ_FIELD_CSTR),
    MW("ucs1",attack1.weaponSound,BZ_FIELD_U32), MW("ucs2",attack2.weaponSound,BZ_FIELD_U32),
    { 0 }
};

#undef MW
#undef MU
#undef MD
#undef MB
#undef MA
#undef MP
#undef MI
#undef M
#endif
